local function primitive(label, acquiredAs, payloadDomain)
    return {
        label = label,
        acquiredAs = acquiredAs,
        payloadDomain = payloadDomain,
    }
end

return {
    AphroditeUpgrade = primitive("Aphrodite", nil, "BoonSource"),
    ApolloUpgrade = primitive("Apollo", nil, "BoonSource"),
    AresUpgrade = primitive("Ares", nil, "BoonSource"),
    DemeterUpgrade = primitive("Demeter", nil, "BoonSource"),
    HephaestusUpgrade = primitive("Hephaestus", nil, "BoonSource"),
    HeraUpgrade = primitive("Hera", nil, "BoonSource"),
    HermesUpgrade = primitive("Hermes", "HermesUpgrade"),
    HestiaUpgrade = primitive("Hestia", nil, "BoonSource"),
    PoseidonUpgrade = primitive("Poseidon", nil, "BoonSource"),
    ZeusUpgrade = primitive("Zeus", nil, "BoonSource"),

    Boon = primitive("Boon", nil, "BoonSource"),
    Devotion = primitive("Trial", nil, "DevotionPair"),
    Story = primitive("Story"),
    ClockworkGoal = primitive("Clockwork Goal"),
    RandomLoot = primitive("Boon", "Boon", "BoonSource"),
    BoostedRandomLoot = primitive("Boosted Boon", "Boon", "BoonSource"),
    BlindBoxLoot = primitive("Mystery Boon", "Boon", "BoonSource"),
    ShopHermesUpgrade = primitive("Hermes Boon", "HermesUpgrade"),

    WeaponUpgrade = primitive("Hammer", "WeaponUpgrade"),
    WeaponUpgradeDrop = primitive("Hammer", "WeaponUpgrade"),
    ChaosWeaponUpgrade = primitive("Anvil", "WeaponUpgrade"),
    MaxHealthDrop = primitive("Max Health"),
    MaxHealthDropSmall = primitive("Tiny Max Health", "MaxHealthDrop"),
    MaxHealthDropBig = primitive("Big Max Health", "MaxHealthDrop"),
    EmptyMaxHealthSmallDrop = primitive("Empty Max Health", "MaxHealthDrop"),
    MaxManaDrop = primitive("Max Magick"),
    MaxManaDropSmall = primitive("Tiny Max Magick", "MaxManaDrop"),
    MaxManaDropBig = primitive("Big Max Magick", "MaxManaDrop"),
    StackUpgrade = primitive("Pom of Power"),
    StackUpgradeBig = primitive("Double Pom", "StackUpgrade"),
    StackUpgradeTriple = primitive("Triple Pom", "StackUpgrade"),
    StoreRewardRandomStack = primitive("Pom Slice", "StackUpgrade"),
    RoomMoneyDrop = primitive("Gold"),
    RoomMoneyTinyDrop = primitive("Tiny Gold", "RoomMoneyDrop"),
    RoomMoneyTripleDrop = primitive("Triple Gold", "RoomMoneyDrop"),
    TalentDrop = primitive("Path of Stars"),
    MinorTalentDrop = primitive("Tiny Path", "TalentDrop"),
    TalentBigDrop = primitive("Big Path", "TalentDrop"),
    SpellDrop = primitive("Selene's Gift"),
    GiftDrop = primitive("Nectar"),
    MetaCurrencyDrop = primitive("Bones"),
    MetaCurrencyBigDrop = primitive("Big Bones", "MetaCurrencyDrop"),
    MetaCardPointsCommonDrop = primitive("Ashes"),
    MetaCardPointsCommonBigDrop = primitive("Big Ashes", "MetaCardPointsCommonDrop"),
    RoomRewardHealDrop = primitive("Heal"),
    HealBigDrop = primitive("Big Heal", "RoomRewardHealDrop"),
    ArmorBoost = primitive("Armor"),
    ArmorBigBoost = primitive("Big Armor", "ArmorBoost"),
    LastStandDrop = primitive("Kiss of Styx"),
    WeaponPointsRareDrop = primitive("Nightmare"),
    CardUpgradePointsDrop = primitive("Moon Dust"),
    CharonPointsDrop = primitive("Obol Points"),
    AirBoost = primitive("Air"),
    EarthBoost = primitive("Earth"),
    FireBoost = primitive("Fire"),
    WaterBoost = primitive("Water"),
    ElementalBoost = primitive("Element"),
}
