return {
    {
        biomeStepKey = "Underworld_F",
        focusedRoomControls = true,
        topology = true,
        materialization = false,
        headlessPipeline = false,
        plannerActive = false,
    },
    {
        biomeStepKey = "Underworld_G",
        focusedRoomControls = true,
        topology = true,
        materialization = false,
        headlessPipeline = false,
        plannerActive = false,
    },
    {
        biomeStepKey = "Underworld_H",
        focusedRoomControls = false,
        topology = false,
        materialization = false,
        headlessPipeline = false,
        plannerActive = false,
    },
    {
        biomeStepKey = "Underworld_I",
        focusedRoomControls = false,
        topology = false,
        materialization = false,
        headlessPipeline = false,
        plannerActive = false,
    },
    {
        biomeStepKey = "Surface_N",
        focusedRoomControls = false,
        topology = false,
        materialization = false,
        headlessPipeline = false,
        plannerActive = false,
    },
    {
        biomeStepKey = "Surface_O",
        focusedRoomControls = false,
        topology = false,
        materialization = false,
        headlessPipeline = false,
        plannerActive = false,
    },
    {
        biomeStepKey = "Surface_P",
        focusedRoomControls = false,
        topology = false,
        materialization = false,
        headlessPipeline = false,
        plannerActive = false,
    },
    {
        biomeStepKey = "Surface_Q",
        focusedRoomControls = false,
        topology = false,
        materialization = false,
        headlessPipeline = false,
        plannerActive = false,
    },
}
