package.path = "./?.lua;./?/init.lua;" .. package.path

local lu = require("luaunit")
dofile("tests/TestFreshSkeleton.lua")
dofile("tests/controls/TestPlannerDraftControl.lua")
dofile("tests/declarations/TestDeclarationCatalog.lua")
dofile("tests/feedback/TestCandidateFeedback.lua")
dofile("tests/forms/TestRouteForm.lua")
dofile("tests/history/TestHistoryBuilder.lua")
dofile("tests/pipeline/TestRoutePipeline.lua")
dofile("tests/ui/TestBiomePanels.lua")
dofile("tests/ui/TestDebugHarness.lua")
dofile("tests/ui/TestFormIdentity.lua")
dofile("tests/ui/TestPlannerState.lua")
dofile("tests/ui/TestPlannerWidgets.lua")
dofile("tests/ui/TestFErebusPanel.lua")
dofile("tests/ui/TestRouteNav.lua")
dofile("tests/ui/TestRouteShell.lua")
dofile("tests/validation/TestRewardValidator.lua")
dofile("tests/validation/TestStructuralValidator.lua")
os.exit(lu.LuaUnit.run())
