package.path = "./?.lua;./?/init.lua;" .. package.path

local lu = require("luaunit")
dofile("tests/TestData.lua")
dofile("tests/TestBiomeDeclarations.lua")
dofile("tests/TestLiveGameValidator.lua")
dofile("tests/TestTimeline.lua")
dofile("tests/TestRouteHistoryBuilder.lua")
dofile("tests/TestRouteHistoryQuery.lua")
dofile("tests/TestRouteHistoryValidator.lua")
dofile("tests/TestRouteUi.lua")
dofile("tests/TestRouteGlobal.lua")
dofile("tests/TestControlForm.lua")
dofile("tests/TestFixedLinearRoute.lua")
dofile("tests/TestClockworkGoalRoute.lua")
dofile("tests/TestHubPylonRoute.lua")
dofile("tests/TestMultiEncounterRoute.lua")
dofile("tests/TestFieldsCageRoute.lua")
dofile("tests/TestRewards.lua")
os.exit(lu.LuaUnit.run())
