package.path = "./?.lua;./?/init.lua;" .. package.path

local lu = require("luaunit")
dofile("tests/TestData.lua")
dofile("tests/TestTimeline.lua")
dofile("tests/TestRouteUi.lua")
dofile("tests/TestRouteGlobal.lua")
dofile("tests/TestRouteNpcs.lua")
dofile("tests/TestRouteFeatures.lua")
dofile("tests/TestFixedLinearRoute.lua")
dofile("tests/TestClockworkGoalRoute.lua")
dofile("tests/TestHubPylonRoute.lua")
dofile("tests/TestMultiEncounterRoute.lua")
dofile("tests/TestFieldsCageRoute.lua")
dofile("tests/TestRewardPlanning.lua")
dofile("tests/TestRewards.lua")
dofile("tests/TestNpcs.lua")
dofile("tests/TestFeatures.lua")
dofile("tests/TestLogicRoutePlan.lua")
dofile("tests/TestLogicRoomRouting.lua")
dofile("tests/TestLogicRewardRouting.lua")
dofile("tests/TestLogicNpcRouting.lua")
dofile("tests/TestLogicFeatureRouting.lua")
os.exit(lu.LuaUnit.run())
