return {
    FixedOpening = { roomKinds = { "Opening" }, localChildLimit = 0 },
    FixedIntro = { roomKinds = { "Intro" }, localChildLimit = 0 },
    FixedPreHub = { roomKinds = { "PreHub" }, localChildLimit = 0 },
    EphyraHub = { roomKinds = { "Hub" }, localChildLimit = 0 },
    StandardCombat = { roomKinds = { "Combat" }, localChildLimit = 0 },
    FieldsCombat = { roomKinds = { "Combat" }, localChildLimit = 3 },
    ClockworkCombat = { roomKinds = { "Combat" }, localChildLimit = 0 },
    EphyraCombat = { roomKinds = { "Combat" }, localChildLimit = 3 },
    ShipCombat = { roomKinds = { "Combat" }, localChildLimit = 2 },
    OlympusCombat = { roomKinds = { "Combat" }, localChildLimit = 0 },
    Story = { roomKinds = { "Bridge", "Story" }, localChildLimit = 0 },
    Fountain = { roomKinds = { "Reprieve" }, localChildLimit = 0 },
    Shop = { roomKinds = { "Shop" }, localChildLimit = 0 },
    Miniboss = { roomKinds = { "Miniboss" }, localChildLimit = 0 },
    Devotion = { roomKinds = { "Devotion" }, localChildLimit = 0 },
    DirectPreboss = { roomKinds = { "Preboss" }, localChildLimit = 0 },
    ForkedPreboss = {
        roomKinds = { "Preboss" },
        localChildLimit = 0,
        freeRewardSlotCapacity = 2,
    },
}
