return {
    biome_depth_unavailable = {
        template = "Room is not valid at this generated depth",
        payload = {},
    },
    encounter_depth_unavailable = {
        template = "Room is not valid at this encounter depth",
        payload = {},
    },
    previous_room_next_tags = {
        template = "Previous planned room only leads to {requiredNextRoomTag}",
        payload = {
            requiredNextRoomTag = {
                fallback = "required rooms",
            },
        },
    },
    variant_encounter_depth_unavailable = {
        template = "{variantLabel} is not valid at this encounter depth",
        payload = {
            variantLabel = {
                fallback = "Variant",
            },
        },
    },
    role_limit = {
        template = "{roleLabel} is already planned",
        payload = {
            roleLabel = {
                fallback = "Room type",
            },
        },
    },
    option_limit = {
        template = "{optionLabel} is already generated",
        payload = {
            optionLabel = {
                fallback = "Room",
            },
        },
    },
    previous_room_exit_count = {
        template = "{previousEntryLabel} exit count is {actualExitCount}; {currentEntryLabel} requires {requiredExitCount}",
        payload = {
            previousEntryLabel = {
                fallback = "Previous room",
            },
            actualExitCount = {
                fallback = "0",
            },
            currentEntryLabel = {
                fallback = "This room",
            },
            requiredExitCount = {
                fallback = "?",
            },
        },
    },
    forced_topology_pressure_unresolved = {
        template = "{topologyForceLabel} was not generated by depth {deadlineBiomeDepthCache} ({generatedCount}/{requiredGeneratedCount} force-window doors generated)",
        payload = {
            topologyForceLabel = {
                fallback = "Forced room",
            },
            deadlineBiomeDepthCache = {
                fallback = "?",
            },
            generatedCount = {
                fallback = "0",
            },
            requiredGeneratedCount = {
                fallback = "?",
            },
        },
    },
    forced_topology_group_unresolved = {
        template = "{topologyGroupLabel} generated {generatedCount}/{requiredGeneratedCount} required doors by depth {deadlineBiomeDepthCache}",
        payload = {
            topologyGroupLabel = {
                fallback = "Forced room group",
            },
            generatedCount = {
                fallback = "0",
            },
            requiredGeneratedCount = {
                fallback = "?",
            },
            deadlineBiomeDepthCache = {
                fallback = "?",
            },
        },
    },
    room_deadline_requirement = {
        template = "{deadlineRequirementLabel} generated {generatedCount}/{requiredGeneratedCount} required rooms by depth {deadlineBiomeDepthCache}",
        payload = {
            deadlineRequirementLabel = {
                fallback = "Required room",
            },
            generatedCount = {
                fallback = "0",
            },
            requiredGeneratedCount = {
                fallback = "?",
            },
            deadlineBiomeDepthCache = {
                fallback = "?",
            },
        },
    },
    thessaly_story_or_shop_deadline = {
        template = "Thessaly requires {deadlineRequirementLabel} by depth {deadlineBiomeDepthCache} ({generatedCount}/{requiredGeneratedCount} generated)",
        payload = {
            deadlineRequirementLabel = {
                fallback = "Circe or Shop",
            },
            deadlineBiomeDepthCache = {
                fallback = "?",
            },
            generatedCount = {
                fallback = "0",
            },
            requiredGeneratedCount = {
                fallback = "1",
            },
        },
    },
    clockwork_preboss_too_early = {
        template = "{clockworkBiomeLabel} {clockworkPrebossLabel} cannot appear before {clockworkProgressionLabel} are complete",
        payload = {
            clockworkBiomeLabel = {
                fallback = "Tartarus",
            },
            clockworkPrebossLabel = {
                fallback = "Preboss",
            },
            clockworkProgressionLabel = {
                fallback = "Clockwork goals",
            },
        },
    },
    clockwork_single_door_goal_required = {
        template = "{clockworkBiomeLabel} single doors need {clockworkGoalLabel} before {clockworkProgressionLabel} are complete",
        payload = {
            clockworkBiomeLabel = {
                fallback = "Tartarus",
            },
            clockworkGoalLabel = {
                fallback = "Goal Room",
            },
            clockworkProgressionLabel = {
                fallback = "Clockwork goals",
            },
        },
    },
    clockwork_goal_door_count = {
        template = "{clockworkBiomeLabel} generated doors need exactly one {clockworkGoalLabel} before {clockworkProgressionLabel} are complete",
        payload = {
            clockworkBiomeLabel = {
                fallback = "Tartarus",
            },
            clockworkGoalLabel = {
                fallback = "Goal Room",
            },
            clockworkProgressionLabel = {
                fallback = "Clockwork goals",
            },
        },
    },
    clockwork_preboss_required = {
        template = "{clockworkBiomeLabel} post-goal doors need {clockworkPrebossLabel}",
        payload = {
            clockworkBiomeLabel = {
                fallback = "Tartarus",
            },
            clockworkPrebossLabel = {
                fallback = "Preboss",
            },
        },
    },
    fields_sibling_combat_cage_count_mismatch = {
        template = "Other Door combat reward count must match Picked Door",
        payload = {},
    },
    sibling_same_room = {
        template = "Other Door cannot reuse current room",
        payload = {},
    },
    sibling_same_sibling_room = {
        template = "Other Door cannot duplicate another door",
        payload = {},
    },
    sibling_room_generated = {
        template = "Other Door room was already generated",
        payload = {},
    },
    sibling_miniboss_after_selected = {
        template = "Other Door miniboss cannot appear after a picked miniboss",
        payload = {},
    },
    sibling_room_planned = {
        template = "Other Door room is already planned on this route",
        payload = {},
    },
    npc_biome_required = {
        template = "{npcLabel} needs Disabled or a target biome",
        payload = {
            npcLabel = {
                fallback = "NPC",
            },
        },
    },
    npc_room_required = {
        template = "{npcLabel} needs a target room",
        payload = {
            npcLabel = {
                fallback = "NPC",
            },
        },
    },
    npc_target_unavailable = {
        template = "{npcLabel} target is no longer valid",
        payload = {
            npcLabel = {
                fallback = "NPC",
            },
        },
    },
    npc_room_occupied = {
        template = "Only one NPC encounter can use the same room",
        payload = {},
    },
    npc_spacing = {
        template = "{npcLabel} is too close to another planned NPC",
        payload = {
            npcLabel = {
                fallback = "NPC",
            },
        },
    },
    duplicate_devotion_god = {
        template = "Trial gods must be different",
        payload = {},
    },
    duplicate_reward_type = {
        template = "Fields cage rewards cannot duplicate non-boon rewards",
        payload = {},
    },
    duplicate_boon_source = {
        template = "Fields cage boon sources must be different",
        payload = {},
    },
    duplicate_shop_group_option = {
        template = "Offers 1 and 2 share one vanilla shop group and cannot duplicate the same reward",
        payload = {},
    },
    unknown = {
        template = "Selection is not valid",
        payload = {},
    },
}
