return {
    biome_depth_unavailable = {
        template = "Room is not valid at this generated depth",
        payload = {},
    },
    encounter_depth_unavailable = {
        template = "Room is not valid at this encounter depth",
        payload = {},
    },
    previous_room_next_tags = {
        template = "Previous planned room only leads to {requiredNextRoomTag} rooms",
        payload = {
            requiredNextRoomTag = {
                fallback = "required",
            },
        },
    },
    variant_encounter_depth_unavailable = {
        template = "{variantLabel} is not valid at this encounter depth",
        payload = {
            variantLabel = {
                fallback = "Variant",
            },
        },
    },
    role_limit = {
        template = "{roleLabel} is already planned",
        payload = {
            roleLabel = {
                fallback = "Room type",
            },
        },
    },
    option_limit = {
        template = "{optionLabel} is already generated",
        payload = {
            optionLabel = {
                fallback = "Room",
            },
        },
    },
    previous_room_exit_count = {
        template = "{previousEntryLabel} exit count is {actualExitCount}; {currentEntryLabel} requires {requiredExitCount}",
        payload = {
            previousEntryLabel = {
                fallback = "Previous room",
            },
            actualExitCount = {
                fallback = "0",
            },
            currentEntryLabel = {
                fallback = "This room",
            },
            requiredExitCount = {
                fallback = "?",
            },
        },
    },
    forced_topology_pressure_unresolved = {
        template = "{topologyForceLabel} was not generated by its deadline",
        payload = {
            topologyForceLabel = {
                fallback = "Forced room",
            },
        },
    },
    forced_topology_group_unresolved = {
        template = "{topologyGroupLabel} was not generated by its deadline",
        payload = {
            topologyGroupLabel = {
                fallback = "Forced room group",
            },
        },
    },
    room_deadline_requirement = {
        template = "{deadlineRequirementLabel} was not generated by its deadline",
        payload = {
            deadlineRequirementLabel = {
                fallback = "Required room",
            },
        },
    },
    thessaly_story_or_shop_deadline = {
        template = "Thessaly requires {deadlineRequirementLabel} by depth {deadlineBiomeDepthCache}",
        payload = {
            deadlineRequirementLabel = {
                fallback = "Circe or Shop",
            },
            deadlineBiomeDepthCache = {
                fallback = "?",
            },
        },
    },
    clockwork_preboss_too_early = {
        template = "{clockworkBiomeLabel} {clockworkPrebossLabel} cannot appear before {clockworkProgressionLabel} are complete",
        payload = {
            clockworkBiomeLabel = {
                fallback = "Tartarus",
            },
            clockworkPrebossLabel = {
                fallback = "Preboss",
            },
            clockworkProgressionLabel = {
                fallback = "Clockwork goals",
            },
        },
    },
    clockwork_single_door_goal_required = {
        template = "{clockworkBiomeLabel} single doors need {clockworkGoalLabel} before {clockworkProgressionLabel} are complete",
        payload = {
            clockworkBiomeLabel = {
                fallback = "Tartarus",
            },
            clockworkGoalLabel = {
                fallback = "Goal Room",
            },
            clockworkProgressionLabel = {
                fallback = "Clockwork goals",
            },
        },
    },
    clockwork_goal_door_count = {
        template = "{clockworkBiomeLabel} generated doors need exactly one {clockworkGoalLabel} before {clockworkProgressionLabel} are complete",
        payload = {
            clockworkBiomeLabel = {
                fallback = "Tartarus",
            },
            clockworkGoalLabel = {
                fallback = "Goal Room",
            },
            clockworkProgressionLabel = {
                fallback = "Clockwork goals",
            },
        },
    },
    clockwork_preboss_required = {
        template = "{clockworkBiomeLabel} post-goal doors need {clockworkPrebossLabel}",
        payload = {
            clockworkBiomeLabel = {
                fallback = "Tartarus",
            },
            clockworkPrebossLabel = {
                fallback = "Preboss",
            },
        },
    },
    fields_sibling_combat_cage_count_mismatch = {
        template = "Other Door combat reward count must match Picked Door",
        payload = {},
    },
    unknown = {
        template = "Selection is not valid",
        payload = {},
    },
}
