return {
    key = "F",
    label = "Erebus",
    routeKey = "Underworld",
    biomeStepKey = "Underworld_F",
    root = { mode = "oneOf", roomKeys = { "F_Opening01", "F_Opening02", "F_Opening03" } },
    terminalRoomKeys = { "F_PreBoss01" },
    batchRuleKey = "Standard",
    topologyBounds = { maxBatches = 10, maxLocalChildrenPerRoom = 0, maxTargets = 20 },
    rooms = {
        {
            key = "F_Opening01",
            kind = "Opening",
            templateKey = "FixedOpening",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ErebusExitDoor" } },
            rewardSurfaceKey = "OpeningReward",
            encounterProfileKey = "F_Opening",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = true,
            localChildren = {},
        },
        {
            key = "F_Opening02",
            kind = "Opening",
            templateKey = "FixedOpening",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ErebusExitDoor" } },
            rewardSurfaceKey = "OpeningReward",
            encounterProfileKey = "F_Opening",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = true,
            localChildren = {},
        },
        {
            key = "F_Opening03",
            kind = "Opening",
            templateKey = "FixedOpening",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ErebusExitDoor" } },
            rewardSurfaceKey = "OpeningReward",
            encounterProfileKey = "F_Opening",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = true,
            localChildren = {},
        },
        {
            key = "F_Combat01",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ErebusExitDoor" } },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeEncounterDepth",
                range = { max = 5 },
                code = "f_combat01_encounter_depth",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat02",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeEncounterDepth",
                range = { max = 5 },
                code = "f_combat02_encounter_depth",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat03",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeEncounterDepth",
                range = { max = 5 },
                code = "f_combat03_encounter_depth",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat04",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeEncounterDepth",
                range = { max = 5 },
                code = "f_combat04_encounter_depth",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat05",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeEncounterDepth",
                range = { min = 5 },
                code = "f_combat05_encounter_depth",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat06",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat07",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat08",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeEncounterDepth",
                range = { max = 5 },
                code = "f_combat08_encounter_depth",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat09",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ErebusExitDoor" } },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeEncounterDepth",
                range = { max = 4 },
                code = "f_combat09_encounter_depth",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat10",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ErebusExitDoor" } },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeEncounterDepth",
                range = { max = 5 },
                code = "f_combat10_encounter_depth",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat11",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeEncounterDepth",
                range = { min = 5 },
                code = "f_combat11_encounter_depth",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat12",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeEncounterDepth",
                range = { min = 5 },
                code = "f_combat12_encounter_depth",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat13",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat14",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeEncounterDepth",
                range = { min = 5 },
                code = "f_combat14_encounter_depth",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat15",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeEncounterDepth",
                range = { min = 5 },
                code = "f_combat15_encounter_depth",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat16",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeEncounterDepth",
                range = { min = 5 },
                code = "f_combat16_encounter_depth",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat17",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeEncounterDepth",
                range = { min = 5 },
                code = "f_combat17_encounter_depth",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat18",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeEncounterDepth",
                range = { min = 5 },
                code = "f_combat18_encounter_depth",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat19",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeEncounterDepth",
                range = { max = 5 },
                code = "f_combat19_encounter_depth",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat20",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeEncounterDepth",
                range = { min = 5 },
                code = "f_combat20_encounter_depth",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat21",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeEncounterDepth",
                range = { max = 5 },
                code = "f_combat21_encounter_depth",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat22",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeEncounterDepth",
                range = { max = 5 },
                code = "f_combat22_encounter_depth",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_MiniBoss01",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ErebusExitDoor" } },
            rewardSurfaceKey = "RunProgressBoonOnly",
            encounterProfileKey = "F_MiniBoss01",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                phase = "room.generate_next",
                requirements = {
                    {
                        kind = "CounterRange",
                        phase = "room.generate_next",
                        axis = "biomeDepthCache",
                        range = { min = 4 },
                        code = "f_miniboss01_too_early",
                    },
                    {
                        kind = "RoomEnteredCount",
                        phase = "room.generate_next",
                        roomKeys = { "F_MiniBoss02", "F_MiniBoss03" },
                        comparison = "==",
                        value = 0,
                        code = "f_miniboss01_other_miniboss_entered",
                    },
                },
                code = "f_miniboss01_eligibility",
            },
            force = { axis = "biomeDepthCache", deadline = 6, kind = "depthWindow", start = 4 },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "F_MiniBoss02",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ErebusExitDoor" } },
            rewardSurfaceKey = "RunProgressBoonOnly",
            encounterProfileKey = "F_MiniBoss02",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                phase = "room.generate_next",
                requirements = {
                    {
                        kind = "CounterRange",
                        phase = "room.generate_next",
                        axis = "biomeDepthCache",
                        range = { min = 4 },
                        code = "f_miniboss02_too_early",
                    },
                    {
                        kind = "RoomEnteredCount",
                        phase = "room.generate_next",
                        roomKeys = { "F_MiniBoss01", "F_MiniBoss03" },
                        comparison = "==",
                        value = 0,
                        code = "f_miniboss02_other_miniboss_entered",
                    },
                },
                code = "f_miniboss02_eligibility",
            },
            force = { axis = "biomeDepthCache", deadline = 6, kind = "depthWindow", start = 4 },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "F_MiniBoss03",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ErebusExitDoor" } },
            rewardSurfaceKey = "RunProgressBoonOnly",
            encounterProfileKey = "F_MiniBoss03",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                phase = "room.generate_next",
                requirements = {
                    {
                        kind = "CounterRange",
                        phase = "room.generate_next",
                        axis = "biomeDepthCache",
                        range = { min = 4 },
                        code = "f_miniboss03_too_early",
                    },
                    {
                        kind = "RoomEnteredCount",
                        phase = "room.generate_next",
                        roomKeys = { "F_MiniBoss01", "F_MiniBoss02" },
                        comparison = "==",
                        value = 0,
                        code = "f_miniboss03_other_miniboss_entered",
                    },
                },
                code = "f_miniboss03_eligibility",
            },
            force = { axis = "biomeDepthCache", deadline = 6, kind = "depthWindow", start = 4 },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "F_Story01",
            kind = "Story",
            templateKey = "Story",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            rewardSurfaceKey = "FixedStory",
            encounterProfileKey = "Story",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeDepthCache",
                range = { max = 8, min = 4 },
                code = "f_story_depth",
            },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "F_Reprieve01",
            kind = "Reprieve",
            templateKey = "Fountain",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "HealthRestore",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeDepthCache",
                range = { max = 8, min = 4 },
                code = "f_reprieve_depth",
            },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "F_Shop01",
            kind = "Shop",
            templateKey = "Shop",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            rewardSurfaceKey = "WorldShop",
            encounterProfileKey = "Shop",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                phase = "room.generate_next",
                requirements = {
                    {
                        kind = "CounterRange",
                        phase = "room.generate_next",
                        axis = "biomeDepthCache",
                        range = { max = 6, min = 4 },
                        code = "f_shop_depth",
                    },
                    {
                        kind = "RequiredMinExits",
                        phase = "room.generate_next",
                        count = 2,
                        code = "f_shop_requires_two_exits",
                    },
                },
                code = "f_shop_eligibility",
            },
            force = { axis = "biomeDepthCache", deadline = 6, kind = "depthWindow", start = 4 },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "F_PreBoss01",
            kind = "Preboss",
            templateKey = "Preboss",
            tags = {},
            exits = { { index = 1, targetMode = "fixedBoss", type = "ErebusExitDoor" } },
            rewardSurfaceKey = "PrebossShopOrFreeReward",
            encounterProfileKey = "Preboss",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeDepthCache",
                range = { min = 10 },
                code = "f_preboss_too_early",
            },
            force = { axis = "biomeDepthCache", deadline = 10, kind = "depthWindow", start = 10 },
            terminal = true,
            fixed = true,
            localChildren = {},
        },
    },
    canonicalCapacity = {
        {
            candidateConstraints = { templateKey = "StandardCombat" },
            contexts = {
                { biomeEncounterDepth = 1, count = 1 },
                { biomeEncounterDepth = 2, count = 2 },
                { biomeEncounterDepth = 3, count = 2 },
                { biomeEncounterDepth = 4, count = 2 },
                { biomeEncounterDepth = 5, count = 2 },
                { biomeEncounterDepth = 6, count = 2 },
                { biomeEncounterDepth = 7, count = 2 },
                { biomeEncounterDepth = 8, count = 2 },
                { biomeEncounterDepth = 9, count = 2 },
                { biomeEncounterDepth = 10, count = 2 },
            },
            familyKey = "F_StandardCombat",
        },
    },
}
