return {
    key = "F",
    label = "Erebus",
    routeKey = "Underworld",
    biomeStepKey = "Underworld_F",
    layout = {
        kind = "LinearBiome",
        start = { mode = "oneOf", roomKeys = { "F_Opening01", "F_Opening02", "F_Opening03" } },
        continuation = { defaultBatchRuleKey = "Standard", overrides = {} },
        terminal = {
            roomKey = "F_PreBoss01",
            transitionRuleKey = "PrebossEntry",
            exitPolicy = { kind = "allExitsTerminal" },
        },
        bounds = { maxBatches = 10, maxTargets = 20 },
    },
    rooms = {
        {
            key = "F_Opening01",
            label = "Opening 01",
            kind = "Opening",
            templateKey = "FixedOpening",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ErebusExitDoor" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress" }, eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion", "RoomMoneyDrop", "MaxHealthDrop", "MaxManaDrop" } },
            encounterProfileKey = "F_Opening",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            localChildren = {},
        },
        {
            key = "F_Opening02",
            label = "Opening 02",
            kind = "Opening",
            templateKey = "FixedOpening",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ErebusExitDoor" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress" }, eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion", "RoomMoneyDrop", "MaxHealthDrop", "MaxManaDrop" } },
            encounterProfileKey = "F_Opening",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            localChildren = {},
        },
        {
            key = "F_Opening03",
            label = "Opening 03",
            kind = "Opening",
            templateKey = "FixedOpening",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ErebusExitDoor" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress" }, eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion", "RoomMoneyDrop", "MaxHealthDrop", "MaxManaDrop" } },
            encounterProfileKey = "F_Opening",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            localChildren = {},
        },
        {
            key = "F_Combat01",
            label = "Combat 01",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ErebusExitDoor" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress" }, eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { max = 5 },
                code = "biome_encounter_depth_out_of_range",
            },
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat02",
            label = "Combat 02",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { max = 5 },
                code = "biome_encounter_depth_out_of_range",
            },
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat03",
            label = "Combat 03",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { max = 5 },
                code = "biome_encounter_depth_out_of_range",
            },
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat04",
            label = "Combat 04",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { max = 5 },
                code = "biome_encounter_depth_out_of_range",
            },
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat05",
            label = "Combat 05",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { min = 5 },
                code = "biome_encounter_depth_out_of_range",
            },
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat06",
            label = "Combat 06",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat07",
            label = "Combat 07",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat08",
            label = "Combat 08",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { max = 5 },
                code = "biome_encounter_depth_out_of_range",
            },
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat09",
            label = "Combat 09",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ErebusExitDoor" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { max = 4 },
                code = "biome_encounter_depth_out_of_range",
            },
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat10",
            label = "Combat 10",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ErebusExitDoor" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { max = 5 },
                code = "biome_encounter_depth_out_of_range",
            },
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat11",
            label = "Combat 11",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { min = 5 },
                code = "biome_encounter_depth_out_of_range",
            },
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat12",
            label = "Combat 12",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { min = 5 },
                code = "biome_encounter_depth_out_of_range",
            },
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat13",
            label = "Combat 13",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat14",
            label = "Combat 14",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { min = 5 },
                code = "biome_encounter_depth_out_of_range",
            },
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat15",
            label = "Combat 15",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { min = 5 },
                code = "biome_encounter_depth_out_of_range",
            },
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat16",
            label = "Combat 16",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { min = 5 },
                code = "biome_encounter_depth_out_of_range",
            },
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat17",
            label = "Combat 17",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { min = 5 },
                code = "biome_encounter_depth_out_of_range",
            },
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat18",
            label = "Combat 18",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { min = 5 },
                code = "biome_encounter_depth_out_of_range",
            },
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat19",
            label = "Combat 19",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { max = 5 },
                code = "biome_encounter_depth_out_of_range",
            },
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat20",
            label = "Combat 20",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { min = 5 },
                code = "biome_encounter_depth_out_of_range",
            },
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat21",
            label = "Combat 21",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { max = 5 },
                code = "biome_encounter_depth_out_of_range",
            },
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_Combat22",
            label = "Combat 22",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { max = 5 },
                code = "biome_encounter_depth_out_of_range",
            },
            canonicalFamily = "F_StandardCombat",
            localChildren = {},
        },
        {
            key = "F_MiniBoss01",
            label = "Root-Stalker",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ErebusExitDoor" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress" }, eligibleRewardTypes = { "Boon" }, ineligibleRewardTypes = {} },
            encounterProfileKey = "F_MiniBoss01",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { min = 4 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RoomEnteredCount",
                        roomKeys = { "F_MiniBoss02", "F_MiniBoss03" },
                        comparison = "==",
                        value = 0,
                        code = "other_miniboss_entered",
                    },
                },
            },
            force = { axis = "biomeDepthCache", deadline = 6, kind = "depthWindow", start = 4 },
            localChildren = {},
        },
        {
            key = "F_MiniBoss02",
            label = "Shadow-Spiller",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ErebusExitDoor" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress" }, eligibleRewardTypes = { "Boon" }, ineligibleRewardTypes = {} },
            encounterProfileKey = "F_MiniBoss02",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { min = 4 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RoomEnteredCount",
                        roomKeys = { "F_MiniBoss01", "F_MiniBoss03" },
                        comparison = "==",
                        value = 0,
                        code = "other_miniboss_entered",
                    },
                },
            },
            force = { axis = "biomeDepthCache", deadline = 6, kind = "depthWindow", start = 4 },
            localChildren = {},
        },
        {
            key = "F_MiniBoss03",
            label = "Phantom",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ErebusExitDoor" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress" }, eligibleRewardTypes = { "Boon" }, ineligibleRewardTypes = {} },
            encounterProfileKey = "F_MiniBoss03",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { min = 4 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RoomEnteredCount",
                        roomKeys = { "F_MiniBoss01", "F_MiniBoss02" },
                        comparison = "==",
                        value = 0,
                        code = "other_miniboss_entered",
                    },
                },
            },
            force = { axis = "biomeDepthCache", deadline = 6, kind = "depthWindow", start = 4 },
            localChildren = {},
        },
        {
            key = "F_Story01",
            label = "Arachne",
            kind = "Story",
            templateKey = "Story",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            incomingReward = { kind = "fixed", rewardType = "Story", constraints = {} },
            encounterProfileKey = "Story",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { max = 8, min = 4 },
                code = "biome_depth_out_of_range",
            },
            localChildren = {},
        },
        {
            key = "F_Reprieve01",
            label = "Fountain",
            kind = "Reprieve",
            templateKey = "Fountain",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "HealthRestore",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { max = 8, min = 4 },
                code = "biome_depth_out_of_range",
            },
            localChildren = {},
        },
        {
            key = "F_Shop01",
            label = "Midshop",
            kind = "Shop",
            templateKey = "Shop",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "ErebusExitDoor" },
                { index = 2, targetMode = "generated", type = "ErebusExitDoor" },
            },
            incomingReward = { kind = "shop", shopProfileKey = "WorldShop" },
            encounterProfileKey = "Shop",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { max = 6, min = 4 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RequiredMinExits",
                        count = 2,
                        code = "insufficient_exits",
                    },
                },
            },
            force = { axis = "biomeDepthCache", deadline = 6, kind = "depthWindow", start = 4 },
            localChildren = {},
        },
        {
            key = "F_PreBoss01",
            label = "Preboss",
            kind = "Preboss",
            templateKey = "ForkedPreboss",
            tags = {},
            exits = { { index = 1, targetMode = "fixedBoss", type = "ErebusExitDoor" } },
            incomingReward = { kind = "shop", shopProfileKey = "WorldShop" },
            entryOfferPolicy = {
                kind = "shopThenFillRemainingExits",
                defaultEntryMode = "Shop",
                freeReward = { kind = "countedChoice", storeKeys = { "RunProgress" }, eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion", "RoomMoneyDrop" } },
                maxFreeRewards = 1,
            },
            encounterProfileKey = "Preboss",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { min = 10 },
                code = "biome_depth_out_of_range",
            },
            force = { axis = "biomeDepthCache", deadline = 10, kind = "depthWindow", start = 10 },
            localChildren = {},
        },
    },
    canonicalCapacity = {
        {
            candidateConstraints = { templateKey = "StandardCombat" },
            contexts = {
                { biomeEncounterDepth = 1, count = 1 },
                { biomeEncounterDepth = 2, count = 2 },
                { biomeEncounterDepth = 3, count = 2 },
                { biomeEncounterDepth = 4, count = 2 },
                { biomeEncounterDepth = 5, count = 2 },
                { biomeEncounterDepth = 6, count = 2 },
                { biomeEncounterDepth = 7, count = 2 },
                { biomeEncounterDepth = 8, count = 2 },
                { biomeEncounterDepth = 9, count = 2 },
                { biomeEncounterDepth = 10, count = 2 },
            },
            familyKey = "F_StandardCombat",
        },
    },
}
