return {
    key = "G",
    label = "Oceanus",
    routeKey = "Underworld",
    biomeStepKey = "Underworld_G",
    root = { mode = "fixed", roomKeys = { "G_Intro" } },
    terminalRoomKeys = { "G_PreBoss01" },
    batchRuleKey = "Standard",
    topologyBounds = { maxBatches = 8, maxLocalChildrenPerRoom = 0, maxTargets = 21 },
    rooms = {
        {
            key = "G_Intro",
            kind = "Intro",
            templateKey = "FixedIntro",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "OceanusExitDoor" } },
            rewardSurfaceKey = "None",
            encounterProfileKey = "FixedIntro",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { exact = 1 },
                code = "biome_depth_out_of_range",
            },
            force = { axis = "biomeDepthCache", deadline = 1, kind = "depthWindow", start = 0 },
            terminal = false,
            fixed = true,
            localChildren = {},
        },
        {
            key = "G_Combat01",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 2, targetMode = "generated", type = "OceanusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { max = 3 },
                code = "biome_encounter_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "G_StandardCombat",
            localChildren = {},
        },
        {
            key = "G_Combat02",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 2, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 3, targetMode = "generated", type = "OceanusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "G_StandardCombat",
            localChildren = {},
        },
        {
            key = "G_Combat03",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 2, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 3, targetMode = "generated", type = "OceanusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { min = 3 },
                code = "biome_encounter_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "G_StandardCombat",
            localChildren = {},
        },
        {
            key = "G_Combat04",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 2, targetMode = "generated", type = "OceanusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { max = 3 },
                code = "biome_encounter_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "G_StandardCombat",
            localChildren = {},
        },
        {
            key = "G_Combat05",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 2, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 3, targetMode = "generated", type = "OceanusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { max = 3 },
                code = "biome_encounter_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "G_StandardCombat",
            localChildren = {},
        },
        {
            key = "G_Combat06",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 2, targetMode = "generated", type = "OceanusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { max = 3 },
                code = "biome_encounter_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "G_StandardCombat",
            localChildren = {},
        },
        {
            key = "G_Combat07",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 2, targetMode = "generated", type = "OceanusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { max = 3 },
                code = "biome_encounter_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "G_StandardCombat",
            localChildren = {},
        },
        {
            key = "G_Combat08",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 2, targetMode = "generated", type = "OceanusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { max = 3 },
                code = "biome_encounter_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "G_StandardCombat",
            localChildren = {},
        },
        {
            key = "G_Combat09",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 2, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 3, targetMode = "generated", type = "OceanusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { min = 3 },
                code = "biome_encounter_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "G_StandardCombat",
            localChildren = {},
        },
        {
            key = "G_Combat10",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 2, targetMode = "generated", type = "OceanusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { min = 3 },
                code = "biome_encounter_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "G_StandardCombat",
            localChildren = {},
        },
        {
            key = "G_Combat11",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 2, targetMode = "generated", type = "OceanusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { min = 3 },
                code = "biome_encounter_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "G_StandardCombat",
            localChildren = {},
        },
        {
            key = "G_Combat12",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 2, targetMode = "generated", type = "OceanusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { min = 3 },
                code = "biome_encounter_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "G_StandardCombat",
            localChildren = {},
        },
        {
            key = "G_Combat13",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 2, targetMode = "generated", type = "OceanusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { min = 3 },
                code = "biome_encounter_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "G_StandardCombat",
            localChildren = {},
        },
        {
            key = "G_Combat14",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 2, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 3, targetMode = "generated", type = "OceanusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { min = 3 },
                code = "biome_encounter_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "G_StandardCombat",
            localChildren = {},
        },
        {
            key = "G_Combat15",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 2, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 3, targetMode = "generated", type = "OceanusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { min = 3 },
                code = "biome_encounter_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "G_StandardCombat",
            localChildren = {},
        },
        {
            key = "G_Combat16",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 2, targetMode = "generated", type = "OceanusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { min = 3 },
                code = "biome_encounter_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "G_StandardCombat",
            localChildren = {},
        },
        {
            key = "G_Combat17",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 2, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 3, targetMode = "generated", type = "OceanusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { min = 3 },
                code = "biome_encounter_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "G_StandardCombat",
            localChildren = {},
        },
        {
            key = "G_Combat18",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 2, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 3, targetMode = "generated", type = "OceanusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { max = 3 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "CounterRange",
                        axis = "biomeEncounterDepth",
                        range = { max = 2 },
                        code = "biome_encounter_depth_out_of_range",
                    },
                },
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "G_StandardCombat",
            localChildren = {},
        },
        {
            key = "G_Combat19",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 2, targetMode = "generated", type = "OceanusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { max = 3 },
                code = "biome_encounter_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "G_StandardCombat",
            localChildren = {},
        },
        {
            key = "G_Combat20",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 2, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 3, targetMode = "generated", type = "OceanusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { max = 3 },
                code = "biome_encounter_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "G_StandardCombat",
            localChildren = {},
        },
        {
            key = "G_MiniBoss01",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 2, targetMode = "generated", type = "OceanusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressBoonOnly",
            encounterProfileKey = "G_MiniBoss01",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { min = 4 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RoomEnteredCount",
                        roomKeys = { "G_MiniBoss02", "G_MiniBoss03" },
                        comparison = "==",
                        value = 0,
                        code = "other_miniboss_entered",
                    },
                },
            },
            force = { axis = "biomeDepthCache", deadline = 7, kind = "depthWindow", start = 4 },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "G_MiniBoss02",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "OceanusExitDoor" } },
            rewardSurfaceKey = "RunProgressBoonOnly",
            encounterProfileKey = "G_MiniBoss02",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { min = 4 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RoomEnteredCount",
                        roomKeys = { "G_MiniBoss01", "G_MiniBoss03" },
                        comparison = "==",
                        value = 0,
                        code = "other_miniboss_entered",
                    },
                },
            },
            force = { axis = "biomeDepthCache", deadline = 7, kind = "depthWindow", start = 4 },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "G_MiniBoss03",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 2, targetMode = "generated", type = "OceanusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressBoonOnly",
            encounterProfileKey = "G_MiniBoss03",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { min = 4 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RoomEnteredCount",
                        roomKeys = { "G_MiniBoss01", "G_MiniBoss02" },
                        comparison = "==",
                        value = 0,
                        code = "other_miniboss_entered",
                    },
                },
            },
            force = { axis = "biomeDepthCache", deadline = 7, kind = "depthWindow", start = 4 },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "G_Story01",
            kind = "Story",
            templateKey = "Story",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "OceanusExitDoor" } },
            rewardSurfaceKey = "FixedStory",
            encounterProfileKey = "Story",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { max = 6, min = 3 },
                code = "biome_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "G_Reprieve01",
            kind = "Reprieve",
            templateKey = "Fountain",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 2, targetMode = "generated", type = "OceanusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "HealthRestore",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { max = 6, min = 4 },
                code = "biome_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "G_Shop01",
            kind = "Shop",
            templateKey = "Shop",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "OceanusExitDoor" },
                { index = 2, targetMode = "generated", type = "OceanusExitDoor" },
            },
            rewardSurfaceKey = "WorldShop",
            encounterProfileKey = "Shop",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { max = 5, min = 3 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RequiredMinExits",
                        count = 2,
                        code = "insufficient_exits",
                    },
                },
            },
            force = { axis = "biomeDepthCache", deadline = 6, kind = "depthWindow", start = 3 },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "G_PreBoss01",
            kind = "Preboss",
            templateKey = "Preboss",
            tags = {},
            exits = { { index = 1, targetMode = "fixedBoss", type = "OceanusExitDoor" } },
            rewardSurfaceKey = "PrebossShopOrFreeReward",
            encounterProfileKey = "Preboss",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { min = 8 },
                code = "biome_depth_out_of_range",
            },
            force = { axis = "biomeDepthCache", deadline = 8, kind = "depthWindow", start = 8 },
            terminal = true,
            fixed = true,
            localChildren = {},
        },
    },
    canonicalCapacity = {
        {
            candidateConstraints = { templateKey = "StandardCombat" },
            contexts = {
                { biomeDepthCache = 1, biomeEncounterDepth = 1, count = 3 },
                { biomeDepthCache = 2, biomeEncounterDepth = 2, count = 3 },
                { biomeDepthCache = 3, biomeEncounterDepth = 3, count = 3 },
                { biomeDepthCache = 4, biomeEncounterDepth = 4, count = 3 },
                { biomeDepthCache = 5, biomeEncounterDepth = 5, count = 3 },
                { biomeDepthCache = 6, biomeEncounterDepth = 6, count = 2 },
                { biomeDepthCache = 7, biomeEncounterDepth = 7, count = 2 },
            },
            familyKey = "G_StandardCombat",
        },
    },
}
