return {
    key = "H",
    label = "Mourning Fields",
    routeKey = "Underworld",
    biomeStepKey = "Underworld_H",
    root = { mode = "fixed", roomKeys = { "H_Intro" } },
    terminalRoomKeys = { "H_PreBoss01" },
    batchRuleKey = "FieldsCageBatch",
    topologyBounds = { maxBatches = 5, maxLocalChildrenPerRoom = 3, maxTargets = 10 },
    biomeState = { fieldsMaxDoorsRolled = { derived = true, max = 2, min = 0 } },
    rooms = {
        {
            key = "H_Intro",
            kind = "Intro",
            templateKey = "FixedIntro",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "FieldsExitDoor" } },
            rewardSurfaceKey = "None",
            encounterProfileKey = "FixedIntro",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { max = 1, min = 0 },
                code = "biome_depth_out_of_range",
            },
            force = { axis = "biomeDepthCache", deadline = 1, kind = "depthWindow", start = 0 },
            terminal = false,
            fixed = true,
            localChildren = {},
        },
        {
            key = "H_Combat01",
            kind = "Combat",
            templateKey = "FieldsCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "FieldsExitDoor" } },
            rewardSurfaceKey = "FieldsCages",
            encounterProfileKey = "FieldsCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "H_FieldsCombat_Cage3",
            localChildren = {
                { key = "cage1", kind = "reward", ordinal = 1 },
                { key = "cage2", kind = "reward", ordinal = 2 },
                { key = "cage3", kind = "reward", ordinal = 3 },
            },
            metadata = { effectiveMaxCageRewards = 3, maxCageRewards = 5 },
        },
        {
            key = "H_Combat02",
            kind = "Combat",
            templateKey = "FieldsCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            rewardSurfaceKey = "FieldsCages",
            encounterProfileKey = "FieldsCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { max = 3 },
                code = "biome_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "H_FieldsCombat_Cage3",
            localChildren = {
                { key = "cage1", kind = "reward", ordinal = 1 },
                { key = "cage2", kind = "reward", ordinal = 2 },
                { key = "cage3", kind = "reward", ordinal = 3 },
            },
            metadata = { effectiveMaxCageRewards = 3, maxCageRewards = 3 },
        },
        {
            key = "H_Combat03",
            kind = "Combat",
            templateKey = "FieldsCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            rewardSurfaceKey = "FieldsCages",
            encounterProfileKey = "FieldsCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "H_FieldsCombat_Cage3",
            localChildren = {
                { key = "cage1", kind = "reward", ordinal = 1 },
                { key = "cage2", kind = "reward", ordinal = 2 },
                { key = "cage3", kind = "reward", ordinal = 3 },
            },
            metadata = { effectiveMaxCageRewards = 3, maxCageRewards = 3 },
        },
        {
            key = "H_Combat04",
            kind = "Combat",
            templateKey = "FieldsCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            rewardSurfaceKey = "FieldsCages",
            encounterProfileKey = "FieldsCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "H_FieldsCombat_Cage3",
            localChildren = {
                { key = "cage1", kind = "reward", ordinal = 1 },
                { key = "cage2", kind = "reward", ordinal = 2 },
                { key = "cage3", kind = "reward", ordinal = 3 },
            },
            metadata = { effectiveMaxCageRewards = 3, maxCageRewards = 4 },
        },
        {
            key = "H_Combat05",
            kind = "Combat",
            templateKey = "FieldsCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            rewardSurfaceKey = "FieldsCages",
            encounterProfileKey = "FieldsCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "H_FieldsCombat_Cage3",
            localChildren = {
                { key = "cage1", kind = "reward", ordinal = 1 },
                { key = "cage2", kind = "reward", ordinal = 2 },
                { key = "cage3", kind = "reward", ordinal = 3 },
            },
            metadata = { effectiveMaxCageRewards = 3, maxCageRewards = 5 },
        },
        {
            key = "H_Combat06",
            kind = "Combat",
            templateKey = "FieldsCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            rewardSurfaceKey = "FieldsCages",
            encounterProfileKey = "FieldsCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "H_FieldsCombat_Cage3",
            localChildren = {
                { key = "cage1", kind = "reward", ordinal = 1 },
                { key = "cage2", kind = "reward", ordinal = 2 },
                { key = "cage3", kind = "reward", ordinal = 3 },
            },
            metadata = { effectiveMaxCageRewards = 3, maxCageRewards = 5 },
        },
        {
            key = "H_Combat07",
            kind = "Combat",
            templateKey = "FieldsCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            rewardSurfaceKey = "FieldsCages",
            encounterProfileKey = "FieldsCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "H_FieldsCombat_Cage3",
            localChildren = {
                { key = "cage1", kind = "reward", ordinal = 1 },
                { key = "cage2", kind = "reward", ordinal = 2 },
                { key = "cage3", kind = "reward", ordinal = 3 },
            },
            metadata = { effectiveMaxCageRewards = 3, maxCageRewards = 3 },
        },
        {
            key = "H_Combat08",
            kind = "Combat",
            templateKey = "FieldsCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            rewardSurfaceKey = "FieldsCages",
            encounterProfileKey = "FieldsCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "H_FieldsCombat_Cage3",
            localChildren = {
                { key = "cage1", kind = "reward", ordinal = 1 },
                { key = "cage2", kind = "reward", ordinal = 2 },
                { key = "cage3", kind = "reward", ordinal = 3 },
            },
            metadata = { effectiveMaxCageRewards = 3, maxCageRewards = 3 },
        },
        {
            key = "H_Combat09",
            kind = "Combat",
            templateKey = "FieldsCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            rewardSurfaceKey = "FieldsCages",
            encounterProfileKey = "FieldsCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { max = 3 },
                code = "biome_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "H_FieldsCombat_Cage2",
            localChildren = {
                { key = "cage1", kind = "reward", ordinal = 1 },
                { key = "cage2", kind = "reward", ordinal = 2 },
                { key = "cage3", kind = "reward", ordinal = 3 },
            },
            metadata = { effectiveMaxCageRewards = 2, maxCageRewards = 2 },
        },
        {
            key = "H_Combat10",
            kind = "Combat",
            templateKey = "FieldsCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            rewardSurfaceKey = "FieldsCages",
            encounterProfileKey = "FieldsCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "H_FieldsCombat_Cage3",
            localChildren = {
                { key = "cage1", kind = "reward", ordinal = 1 },
                { key = "cage2", kind = "reward", ordinal = 2 },
                { key = "cage3", kind = "reward", ordinal = 3 },
            },
            metadata = { effectiveMaxCageRewards = 3, maxCageRewards = 5 },
        },
        {
            key = "H_Combat11",
            kind = "Combat",
            templateKey = "FieldsCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            rewardSurfaceKey = "FieldsCages",
            encounterProfileKey = "FieldsCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "H_FieldsCombat_Cage3",
            localChildren = {
                { key = "cage1", kind = "reward", ordinal = 1 },
                { key = "cage2", kind = "reward", ordinal = 2 },
                { key = "cage3", kind = "reward", ordinal = 3 },
            },
            metadata = { effectiveMaxCageRewards = 3, maxCageRewards = 5 },
        },
        {
            key = "H_Combat12",
            kind = "Combat",
            templateKey = "FieldsCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            rewardSurfaceKey = "FieldsCages",
            encounterProfileKey = "FieldsCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "H_FieldsCombat_Cage3",
            localChildren = {
                { key = "cage1", kind = "reward", ordinal = 1 },
                { key = "cage2", kind = "reward", ordinal = 2 },
                { key = "cage3", kind = "reward", ordinal = 3 },
            },
            metadata = { effectiveMaxCageRewards = 3, maxCageRewards = 3 },
        },
        {
            key = "H_Combat13",
            kind = "Combat",
            templateKey = "FieldsCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            rewardSurfaceKey = "FieldsCages",
            encounterProfileKey = "FieldsCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { max = 3 },
                code = "biome_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "H_FieldsCombat_Cage2",
            localChildren = {
                { key = "cage1", kind = "reward", ordinal = 1 },
                { key = "cage2", kind = "reward", ordinal = 2 },
                { key = "cage3", kind = "reward", ordinal = 3 },
            },
            metadata = { effectiveMaxCageRewards = 2, maxCageRewards = 2 },
        },
        {
            key = "H_Combat14",
            kind = "Combat",
            templateKey = "FieldsCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            rewardSurfaceKey = "FieldsCages",
            encounterProfileKey = "FieldsCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { max = 3 },
                code = "biome_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "H_FieldsCombat_Cage2",
            localChildren = {
                { key = "cage1", kind = "reward", ordinal = 1 },
                { key = "cage2", kind = "reward", ordinal = 2 },
                { key = "cage3", kind = "reward", ordinal = 3 },
            },
            metadata = { effectiveMaxCageRewards = 2, maxCageRewards = 2 },
        },
        {
            key = "H_Combat15",
            kind = "Combat",
            templateKey = "FieldsCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            rewardSurfaceKey = "FieldsCages",
            encounterProfileKey = "FieldsCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { max = 3 },
                code = "biome_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "H_FieldsCombat_Cage3",
            localChildren = {
                { key = "cage1", kind = "reward", ordinal = 1 },
                { key = "cage2", kind = "reward", ordinal = 2 },
                { key = "cage3", kind = "reward", ordinal = 3 },
            },
            metadata = { effectiveMaxCageRewards = 3, maxCageRewards = 3 },
        },
        {
            key = "H_MiniBoss01",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            rewardSurfaceKey = "RunProgressBoonOnly",
            encounterProfileKey = "H_MiniBoss01",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { min = 2 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RoomEnteredCount",
                        roomKeys = { "H_MiniBoss02" },
                        comparison = "==",
                        value = 0,
                        code = "other_miniboss_entered",
                    },
                },
            },
            force = { axis = "biomeDepthCache", deadline = 4, kind = "depthWindow", start = 2 },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "H_MiniBoss02",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "FieldsExitDoor" } },
            rewardSurfaceKey = "RunProgressBoonOnly",
            encounterProfileKey = "H_MiniBoss02",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { min = 2 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RoomEnteredCount",
                        roomKeys = { "H_MiniBoss01" },
                        comparison = "==",
                        value = 0,
                        code = "other_miniboss_entered",
                    },
                },
            },
            force = { axis = "biomeDepthCache", deadline = 4, kind = "depthWindow", start = 2 },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "H_Bridge01",
            kind = "Bridge",
            templateKey = "FieldsBridge",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            rewardSurfaceKey = "FixedStory",
            encounterProfileKey = "FieldsBridge",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "EnteredKindCount",
                range = { max = 2, min = 2 },
                roomKinds = { "Combat", "Miniboss" },
                code = "entered_room_kind_count_out_of_range",
            },
            force = { kind = "always" },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "H_PreBoss01",
            kind = "Preboss",
            templateKey = "Preboss",
            tags = {},
            exits = { { index = 1, targetMode = "fixedBoss", type = "FieldsExitDoor" } },
            rewardSurfaceKey = "PrebossShopOrFreeReward",
            encounterProfileKey = "Preboss",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "EnteredKindCount",
                range = { min = 4 },
                roomKinds = { "Combat", "Miniboss", "Bridge" },
                code = "entered_room_kind_count_out_of_range",
            },
            force = { kind = "always" },
            terminal = true,
            fixed = true,
            localChildren = {},
        },
    },
    canonicalCapacity = {
        {
            candidateConstraints = { metadata = { effectiveMaxCageRewards = 2 }, templateKey = "FieldsCombat" },
            contexts = { { biomeDepthCache = 1, count = 1 }, { biomeDepthCache = 2, count = 1 }, { biomeDepthCache = 3, count = 1 } },
            familyKey = "H_FieldsCombat_Cage2",
        },
        {
            candidateConstraints = { metadata = { effectiveMaxCageRewards = 3 }, templateKey = "FieldsCombat" },
            contexts = {
                { biomeDepthCache = 1, count = 2 },
                { biomeDepthCache = 2, count = 2 },
                { biomeDepthCache = 3, count = 2 },
                { biomeDepthCache = 4, count = 2 },
            },
            familyKey = "H_FieldsCombat_Cage3",
        },
    },
}
