return {
    key = "H",
    label = "Mourning Fields",
    routeKey = "Underworld",
    biomeStepKey = "Underworld_H",
    layout = {
        kind = "LinearBiome",
        start = { mode = "fixed", roomKeys = { "H_Intro" } },
        continuation = { defaultBatchRuleKey = "FieldsCageBatch", overrides = {} },
        terminal = {
            roomKey = "H_PreBoss01",
            transitionRuleKey = "PrebossEntry",
            exitPolicy = { kind = "allExitsTerminal" },
        },
        bounds = { maxBatches = 5, maxTargets = 10 },
    },
    biomeState = { fieldsMaxDoorsRolled = { derived = true, max = 2, min = 0 } },
    rooms = {
        {
            key = "H_Intro",
            label = "Entrance",
            kind = "Intro",
            templateKey = "FixedIntro",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "FieldsExitDoor" } },
            incomingReward = { kind = "none" },
            encounterProfileKey = "FixedIntro",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { max = 1, min = 0 },
                code = "biome_depth_out_of_range",
            },
            force = { axis = "biomeDepthCache", deadline = 1, kind = "depthWindow", start = 0 },
            localChildren = {},
        },
        {
            key = "H_Combat01",
            label = "Combat 01",
            kind = "Combat",
            templateKey = "FieldsCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "FieldsExitDoor" } },
            incomingReward = {
                kind = "localSlots",
                maxSlots = 3,
                choice = {
                    kind = "countedChoice",
                    storeKeys = { "RunProgress" },
                    eligibleRewardTypes = {},
                    ineligibleRewardTypes = { "Devotion" },
                },
                constraints = { "UniqueNonBoonRewardTypes", "UniqueBoonSources" },
            },
            encounterProfileKey = "FieldsCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "H_FieldsCombat_Cage3",
            localChildren = {
                { key = "cage1", kind = "reward", ordinal = 1 },
                { key = "cage2", kind = "reward", ordinal = 2 },
                { key = "cage3", kind = "reward", ordinal = 3 },
            },
            metadata = { effectiveMaxCageRewards = 3, maxCageRewards = 5 },
        },
        {
            key = "H_Combat02",
            label = "Combat 02",
            kind = "Combat",
            templateKey = "FieldsCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            incomingReward = {
                kind = "localSlots",
                maxSlots = 3,
                choice = {
                    kind = "countedChoice",
                    storeKeys = { "RunProgress" },
                    eligibleRewardTypes = {},
                    ineligibleRewardTypes = { "Devotion" },
                },
                constraints = { "UniqueNonBoonRewardTypes", "UniqueBoonSources" },
            },
            encounterProfileKey = "FieldsCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { max = 3 },
                code = "biome_depth_out_of_range",
            },
            canonicalFamily = "H_FieldsCombat_Cage3",
            localChildren = {
                { key = "cage1", kind = "reward", ordinal = 1 },
                { key = "cage2", kind = "reward", ordinal = 2 },
                { key = "cage3", kind = "reward", ordinal = 3 },
            },
            metadata = { effectiveMaxCageRewards = 3, maxCageRewards = 3 },
        },
        {
            key = "H_Combat03",
            label = "Combat 03",
            kind = "Combat",
            templateKey = "FieldsCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            incomingReward = {
                kind = "localSlots",
                maxSlots = 3,
                choice = {
                    kind = "countedChoice",
                    storeKeys = { "RunProgress" },
                    eligibleRewardTypes = {},
                    ineligibleRewardTypes = { "Devotion" },
                },
                constraints = { "UniqueNonBoonRewardTypes", "UniqueBoonSources" },
            },
            encounterProfileKey = "FieldsCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "H_FieldsCombat_Cage3",
            localChildren = {
                { key = "cage1", kind = "reward", ordinal = 1 },
                { key = "cage2", kind = "reward", ordinal = 2 },
                { key = "cage3", kind = "reward", ordinal = 3 },
            },
            metadata = { effectiveMaxCageRewards = 3, maxCageRewards = 3 },
        },
        {
            key = "H_Combat04",
            label = "Combat 04",
            kind = "Combat",
            templateKey = "FieldsCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            incomingReward = {
                kind = "localSlots",
                maxSlots = 3,
                choice = {
                    kind = "countedChoice",
                    storeKeys = { "RunProgress" },
                    eligibleRewardTypes = {},
                    ineligibleRewardTypes = { "Devotion" },
                },
                constraints = { "UniqueNonBoonRewardTypes", "UniqueBoonSources" },
            },
            encounterProfileKey = "FieldsCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "H_FieldsCombat_Cage3",
            localChildren = {
                { key = "cage1", kind = "reward", ordinal = 1 },
                { key = "cage2", kind = "reward", ordinal = 2 },
                { key = "cage3", kind = "reward", ordinal = 3 },
            },
            metadata = { effectiveMaxCageRewards = 3, maxCageRewards = 4 },
        },
        {
            key = "H_Combat05",
            label = "Combat 05",
            kind = "Combat",
            templateKey = "FieldsCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            incomingReward = {
                kind = "localSlots",
                maxSlots = 3,
                choice = {
                    kind = "countedChoice",
                    storeKeys = { "RunProgress" },
                    eligibleRewardTypes = {},
                    ineligibleRewardTypes = { "Devotion" },
                },
                constraints = { "UniqueNonBoonRewardTypes", "UniqueBoonSources" },
            },
            encounterProfileKey = "FieldsCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "H_FieldsCombat_Cage3",
            localChildren = {
                { key = "cage1", kind = "reward", ordinal = 1 },
                { key = "cage2", kind = "reward", ordinal = 2 },
                { key = "cage3", kind = "reward", ordinal = 3 },
            },
            metadata = { effectiveMaxCageRewards = 3, maxCageRewards = 5 },
        },
        {
            key = "H_Combat06",
            label = "Combat 06",
            kind = "Combat",
            templateKey = "FieldsCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            incomingReward = {
                kind = "localSlots",
                maxSlots = 3,
                choice = {
                    kind = "countedChoice",
                    storeKeys = { "RunProgress" },
                    eligibleRewardTypes = {},
                    ineligibleRewardTypes = { "Devotion" },
                },
                constraints = { "UniqueNonBoonRewardTypes", "UniqueBoonSources" },
            },
            encounterProfileKey = "FieldsCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "H_FieldsCombat_Cage3",
            localChildren = {
                { key = "cage1", kind = "reward", ordinal = 1 },
                { key = "cage2", kind = "reward", ordinal = 2 },
                { key = "cage3", kind = "reward", ordinal = 3 },
            },
            metadata = { effectiveMaxCageRewards = 3, maxCageRewards = 5 },
        },
        {
            key = "H_Combat07",
            label = "Combat 07",
            kind = "Combat",
            templateKey = "FieldsCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            incomingReward = {
                kind = "localSlots",
                maxSlots = 3,
                choice = {
                    kind = "countedChoice",
                    storeKeys = { "RunProgress" },
                    eligibleRewardTypes = {},
                    ineligibleRewardTypes = { "Devotion" },
                },
                constraints = { "UniqueNonBoonRewardTypes", "UniqueBoonSources" },
            },
            encounterProfileKey = "FieldsCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "H_FieldsCombat_Cage3",
            localChildren = {
                { key = "cage1", kind = "reward", ordinal = 1 },
                { key = "cage2", kind = "reward", ordinal = 2 },
                { key = "cage3", kind = "reward", ordinal = 3 },
            },
            metadata = { effectiveMaxCageRewards = 3, maxCageRewards = 3 },
        },
        {
            key = "H_Combat08",
            label = "Combat 08",
            kind = "Combat",
            templateKey = "FieldsCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            incomingReward = {
                kind = "localSlots",
                maxSlots = 3,
                choice = {
                    kind = "countedChoice",
                    storeKeys = { "RunProgress" },
                    eligibleRewardTypes = {},
                    ineligibleRewardTypes = { "Devotion" },
                },
                constraints = { "UniqueNonBoonRewardTypes", "UniqueBoonSources" },
            },
            encounterProfileKey = "FieldsCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "H_FieldsCombat_Cage3",
            localChildren = {
                { key = "cage1", kind = "reward", ordinal = 1 },
                { key = "cage2", kind = "reward", ordinal = 2 },
                { key = "cage3", kind = "reward", ordinal = 3 },
            },
            metadata = { effectiveMaxCageRewards = 3, maxCageRewards = 3 },
        },
        {
            key = "H_Combat09",
            label = "Combat 09",
            kind = "Combat",
            templateKey = "FieldsCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            incomingReward = {
                kind = "localSlots",
                maxSlots = 3,
                choice = {
                    kind = "countedChoice",
                    storeKeys = { "RunProgress" },
                    eligibleRewardTypes = {},
                    ineligibleRewardTypes = { "Devotion" },
                },
                constraints = { "UniqueNonBoonRewardTypes", "UniqueBoonSources" },
            },
            encounterProfileKey = "FieldsCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { max = 3 },
                code = "biome_depth_out_of_range",
            },
            canonicalFamily = "H_FieldsCombat_Cage2",
            localChildren = {
                { key = "cage1", kind = "reward", ordinal = 1 },
                { key = "cage2", kind = "reward", ordinal = 2 },
                { key = "cage3", kind = "reward", ordinal = 3 },
            },
            metadata = { effectiveMaxCageRewards = 2, maxCageRewards = 2 },
        },
        {
            key = "H_Combat10",
            label = "Combat 10",
            kind = "Combat",
            templateKey = "FieldsCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            incomingReward = {
                kind = "localSlots",
                maxSlots = 3,
                choice = {
                    kind = "countedChoice",
                    storeKeys = { "RunProgress" },
                    eligibleRewardTypes = {},
                    ineligibleRewardTypes = { "Devotion" },
                },
                constraints = { "UniqueNonBoonRewardTypes", "UniqueBoonSources" },
            },
            encounterProfileKey = "FieldsCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "H_FieldsCombat_Cage3",
            localChildren = {
                { key = "cage1", kind = "reward", ordinal = 1 },
                { key = "cage2", kind = "reward", ordinal = 2 },
                { key = "cage3", kind = "reward", ordinal = 3 },
            },
            metadata = { effectiveMaxCageRewards = 3, maxCageRewards = 5 },
        },
        {
            key = "H_Combat11",
            label = "Combat 11",
            kind = "Combat",
            templateKey = "FieldsCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            incomingReward = {
                kind = "localSlots",
                maxSlots = 3,
                choice = {
                    kind = "countedChoice",
                    storeKeys = { "RunProgress" },
                    eligibleRewardTypes = {},
                    ineligibleRewardTypes = { "Devotion" },
                },
                constraints = { "UniqueNonBoonRewardTypes", "UniqueBoonSources" },
            },
            encounterProfileKey = "FieldsCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "H_FieldsCombat_Cage3",
            localChildren = {
                { key = "cage1", kind = "reward", ordinal = 1 },
                { key = "cage2", kind = "reward", ordinal = 2 },
                { key = "cage3", kind = "reward", ordinal = 3 },
            },
            metadata = { effectiveMaxCageRewards = 3, maxCageRewards = 5 },
        },
        {
            key = "H_Combat12",
            label = "Combat 12",
            kind = "Combat",
            templateKey = "FieldsCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            incomingReward = {
                kind = "localSlots",
                maxSlots = 3,
                choice = {
                    kind = "countedChoice",
                    storeKeys = { "RunProgress" },
                    eligibleRewardTypes = {},
                    ineligibleRewardTypes = { "Devotion" },
                },
                constraints = { "UniqueNonBoonRewardTypes", "UniqueBoonSources" },
            },
            encounterProfileKey = "FieldsCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "H_FieldsCombat_Cage3",
            localChildren = {
                { key = "cage1", kind = "reward", ordinal = 1 },
                { key = "cage2", kind = "reward", ordinal = 2 },
                { key = "cage3", kind = "reward", ordinal = 3 },
            },
            metadata = { effectiveMaxCageRewards = 3, maxCageRewards = 3 },
        },
        {
            key = "H_Combat13",
            label = "Combat 13",
            kind = "Combat",
            templateKey = "FieldsCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            incomingReward = {
                kind = "localSlots",
                maxSlots = 3,
                choice = {
                    kind = "countedChoice",
                    storeKeys = { "RunProgress" },
                    eligibleRewardTypes = {},
                    ineligibleRewardTypes = { "Devotion" },
                },
                constraints = { "UniqueNonBoonRewardTypes", "UniqueBoonSources" },
            },
            encounterProfileKey = "FieldsCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { max = 3 },
                code = "biome_depth_out_of_range",
            },
            canonicalFamily = "H_FieldsCombat_Cage2",
            localChildren = {
                { key = "cage1", kind = "reward", ordinal = 1 },
                { key = "cage2", kind = "reward", ordinal = 2 },
                { key = "cage3", kind = "reward", ordinal = 3 },
            },
            metadata = { effectiveMaxCageRewards = 2, maxCageRewards = 2 },
        },
        {
            key = "H_Combat14",
            label = "Combat 14",
            kind = "Combat",
            templateKey = "FieldsCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            incomingReward = {
                kind = "localSlots",
                maxSlots = 3,
                choice = {
                    kind = "countedChoice",
                    storeKeys = { "RunProgress" },
                    eligibleRewardTypes = {},
                    ineligibleRewardTypes = { "Devotion" },
                },
                constraints = { "UniqueNonBoonRewardTypes", "UniqueBoonSources" },
            },
            encounterProfileKey = "FieldsCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { max = 3 },
                code = "biome_depth_out_of_range",
            },
            canonicalFamily = "H_FieldsCombat_Cage2",
            localChildren = {
                { key = "cage1", kind = "reward", ordinal = 1 },
                { key = "cage2", kind = "reward", ordinal = 2 },
                { key = "cage3", kind = "reward", ordinal = 3 },
            },
            metadata = { effectiveMaxCageRewards = 2, maxCageRewards = 2 },
        },
        {
            key = "H_Combat15",
            label = "Combat 15",
            kind = "Combat",
            templateKey = "FieldsCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            incomingReward = {
                kind = "localSlots",
                maxSlots = 3,
                choice = {
                    kind = "countedChoice",
                    storeKeys = { "RunProgress" },
                    eligibleRewardTypes = {},
                    ineligibleRewardTypes = { "Devotion" },
                },
                constraints = { "UniqueNonBoonRewardTypes", "UniqueBoonSources" },
            },
            encounterProfileKey = "FieldsCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { max = 3 },
                code = "biome_depth_out_of_range",
            },
            canonicalFamily = "H_FieldsCombat_Cage3",
            localChildren = {
                { key = "cage1", kind = "reward", ordinal = 1 },
                { key = "cage2", kind = "reward", ordinal = 2 },
                { key = "cage3", kind = "reward", ordinal = 3 },
            },
            metadata = { effectiveMaxCageRewards = 3, maxCageRewards = 3 },
        },
        {
            key = "H_MiniBoss01",
            label = "Phantom",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress" }, eligibleRewardTypes = { "Boon" }, ineligibleRewardTypes = {} },
            encounterProfileKey = "H_MiniBoss01",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { min = 2 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RoomEnteredCount",
                        roomKeys = { "H_MiniBoss02" },
                        comparison = "==",
                        value = 0,
                        code = "other_miniboss_entered",
                    },
                },
            },
            force = { axis = "biomeDepthCache", deadline = 4, kind = "depthWindow", start = 2 },
            localChildren = {},
        },
        {
            key = "H_MiniBoss02",
            label = "Queen Lamia",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "FieldsExitDoor" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress" }, eligibleRewardTypes = { "Boon" }, ineligibleRewardTypes = {} },
            encounterProfileKey = "H_MiniBoss02",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { min = 2 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RoomEnteredCount",
                        roomKeys = { "H_MiniBoss01" },
                        comparison = "==",
                        value = 0,
                        code = "other_miniboss_entered",
                    },
                },
            },
            force = { axis = "biomeDepthCache", deadline = 4, kind = "depthWindow", start = 2 },
            localChildren = {},
        },
        {
            key = "H_Bridge01",
            label = "Echo",
            kind = "Bridge",
            templateKey = "Story",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "FieldsExitDoor" },
                { index = 2, targetMode = "generated", type = "FieldsExitDoor" },
            },
            incomingReward = { kind = "fixed", rewardType = "Story", constraints = {} },
            encounterProfileKey = "FieldsBridge",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "EnteredKindCount",
                range = { max = 2, min = 2 },
                roomKinds = { "Combat", "Miniboss" },
                code = "entered_room_kind_count_out_of_range",
            },
            force = { kind = "always" },
            localChildren = {},
        },
        {
            key = "H_PreBoss01",
            label = "Preboss",
            kind = "Preboss",
            templateKey = "ForkedPreboss",
            tags = {},
            exits = { { index = 1, targetMode = "fixedBoss", type = "FieldsExitDoor" } },
            incomingReward = { kind = "shop", shopProfileKey = "WorldShop" },
            entryOfferPolicy = {
                kind = "shopThenFillRemainingExits",
                freeReward = { kind = "countedChoice", storeKeys = { "RunProgress" }, eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion", "RoomMoneyDrop" } },
                maxFreeRewards = 1,
            },
            encounterProfileKey = "Preboss",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "EnteredKindCount",
                range = { min = 4 },
                roomKinds = { "Combat", "Miniboss", "Bridge" },
                code = "entered_room_kind_count_out_of_range",
            },
            force = { kind = "always" },
            localChildren = {},
        },
    },
    canonicalCapacity = {
        {
            candidateConstraints = { metadata = { effectiveMaxCageRewards = 2 }, templateKey = "FieldsCombat" },
            contexts = { { biomeDepthCache = 1, count = 1 }, { biomeDepthCache = 2, count = 1 }, { biomeDepthCache = 3, count = 1 } },
            familyKey = "H_FieldsCombat_Cage2",
        },
        {
            candidateConstraints = { metadata = { effectiveMaxCageRewards = 3 }, templateKey = "FieldsCombat" },
            contexts = {
                { biomeDepthCache = 1, count = 2 },
                { biomeDepthCache = 2, count = 2 },
                { biomeDepthCache = 3, count = 2 },
                { biomeDepthCache = 4, count = 2 },
            },
            familyKey = "H_FieldsCombat_Cage3",
        },
    },
}
