return {
    key = "I",
    label = "Tartarus",
    routeKey = "Underworld",
    biomeStepKey = "Underworld_I",
    root = { mode = "fixed", roomKeys = { "I_Intro" } },
    terminalRoomKeys = { "I_PreBoss01", "I_PreBoss02" },
    batchRuleKey = "ClockworkDoorBatch",
    topologyBounds = { maxBatches = 12, maxLocalChildrenPerRoom = 0, maxTargets = 24 },
    biomeState = {
        initialGoals = { authored = false, value = 5 },
        maxNonGoalRewards = { authored = true, values = { 3, 4, 5, 6 } },
    },
    rooms = {
        {
            key = "I_Intro",
            kind = "Intro",
            templateKey = "FixedIntro",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" } },
            rewardSurfaceKey = "None",
            encounterProfileKey = "FixedIntro",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            force = { axis = "biomeDepthCache", deadline = 1, kind = "depthWindow", start = 0 },
            terminal = false,
            fixed = true,
            localChildren = {},
        },
        {
            key = "I_Combat01",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" },
                { index = 2, targetMode = "generated", type = "CWTartarusExitDoor" },
            },
            rewardSurfaceKey = "ClockworkGoalOrTartarus",
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "ClockworkCapacity",
                phase = "room.generate_next",
                counter = "nonGoalRewardsAcquired",
                reserve = 1,
                code = "i_combat01_requires_extension_capacity",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat02",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" } },
            rewardSurfaceKey = "ClockworkGoalOrTartarus",
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat03",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" },
                { index = 2, targetMode = "generated", type = "CWTartarusExitDoor" },
            },
            rewardSurfaceKey = "ClockworkGoalOrTartarus",
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "ClockworkCapacity",
                phase = "room.generate_next",
                counter = "nonGoalRewardsAcquired",
                reserve = 1,
                code = "i_combat03_requires_extension_capacity",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat04",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" },
                { index = 2, targetMode = "generated", type = "CWTartarusExitDoor" },
            },
            rewardSurfaceKey = "ClockworkGoalOrTartarus",
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "ClockworkCapacity",
                phase = "room.generate_next",
                counter = "nonGoalRewardsAcquired",
                reserve = 1,
                code = "i_combat04_requires_extension_capacity",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat05",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" } },
            rewardSurfaceKey = "ClockworkGoalOrTartarus",
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat06",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" } },
            rewardSurfaceKey = "ClockworkGoalOrTartarus",
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat07",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" } },
            rewardSurfaceKey = "ClockworkGoalOrTartarus",
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat08",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" } },
            rewardSurfaceKey = "ClockworkGoalOrTartarus",
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat09",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" },
                { index = 2, targetMode = "generated", type = "CWTartarusExitDoor" },
            },
            rewardSurfaceKey = "ClockworkGoalOrTartarus",
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "ClockworkCapacity",
                phase = "room.generate_next",
                counter = "nonGoalRewardsAcquired",
                reserve = 1,
                code = "i_combat09_requires_extension_capacity",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat10",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" },
                { index = 2, targetMode = "generated", type = "CWTartarusExitDoor" },
            },
            rewardSurfaceKey = "ClockworkGoalOrTartarus",
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "ClockworkCapacity",
                phase = "room.generate_next",
                counter = "nonGoalRewardsAcquired",
                reserve = 1,
                code = "i_combat10_requires_extension_capacity",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat11",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" },
                { index = 2, targetMode = "generated", type = "CWTartarusExitDoor" },
            },
            rewardSurfaceKey = "ClockworkGoalOrTartarus",
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "ClockworkCapacity",
                phase = "room.generate_next",
                counter = "nonGoalRewardsAcquired",
                reserve = 1,
                code = "i_combat11_requires_extension_capacity",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat12",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" },
                { index = 2, targetMode = "generated", type = "CWTartarusExitDoor" },
            },
            rewardSurfaceKey = "ClockworkGoalOrTartarus",
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "ClockworkCapacity",
                phase = "room.generate_next",
                counter = "nonGoalRewardsAcquired",
                reserve = 1,
                code = "i_combat12_requires_extension_capacity",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat13",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" } },
            rewardSurfaceKey = "ClockworkGoalOrTartarus",
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat14",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" } },
            rewardSurfaceKey = "ClockworkGoalOrTartarus",
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat15",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" },
                { index = 2, targetMode = "generated", type = "CWTartarusExitDoor" },
            },
            rewardSurfaceKey = "ClockworkGoalOrTartarus",
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "ClockworkCapacity",
                phase = "room.generate_next",
                counter = "nonGoalRewardsAcquired",
                reserve = 1,
                code = "i_combat15_requires_extension_capacity",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat16",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" } },
            rewardSurfaceKey = "ClockworkGoalOrTartarus",
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat17",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" } },
            rewardSurfaceKey = "ClockworkGoalOrTartarus",
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat18",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" },
                { index = 2, targetMode = "generated", type = "CWTartarusExitDoor" },
            },
            rewardSurfaceKey = "ClockworkGoalOrTartarus",
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "ClockworkCapacity",
                phase = "room.generate_next",
                counter = "nonGoalRewardsAcquired",
                reserve = 1,
                code = "i_combat18_requires_extension_capacity",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat19",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" } },
            rewardSurfaceKey = "ClockworkGoalOrTartarus",
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat20",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" } },
            rewardSurfaceKey = "ClockworkGoalOrTartarus",
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat21",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" },
                { index = 2, targetMode = "generated", type = "CWTartarusExitDoor" },
            },
            rewardSurfaceKey = "ClockworkGoalOrTartarus",
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "ClockworkCapacity",
                phase = "room.generate_next",
                counter = "nonGoalRewardsAcquired",
                reserve = 1,
                code = "i_combat21_requires_extension_capacity",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat22",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" },
                { index = 2, targetMode = "generated", type = "CWTartarusExitDoor" },
            },
            rewardSurfaceKey = "ClockworkGoalOrTartarus",
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "ClockworkCapacity",
                phase = "room.generate_next",
                counter = "nonGoalRewardsAcquired",
                reserve = 1,
                code = "i_combat22_requires_extension_capacity",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat23",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" } },
            rewardSurfaceKey = "ClockworkGoalOrTartarus",
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat24",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" } },
            rewardSurfaceKey = "ClockworkGoalOrTartarus",
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeDepthCache",
                range = { max = 5 },
                code = "i_combat24_biome_depth",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Reprieve01",
            kind = "Reprieve",
            templateKey = "Fountain",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" },
                { index = 2, targetMode = "generated", type = "CWTartarusExitDoor" },
            },
            rewardSurfaceKey = "TartarusNoDevotion",
            encounterProfileKey = "HealthRestore",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                phase = "room.generate_next",
                requirements = {
                    {
                        kind = "CounterRange",
                        phase = "room.generate_next",
                        axis = "biomeDepthCache",
                        range = { min = 4 },
                        code = "i_reprieve_too_early",
                    },
                    {
                        kind = "CurrentRoomCreationExclusion",
                        phase = "room.generate_next",
                        roomKeys = { "I_Story01", "I_Reprieve01", "I_MiniBoss01", "I_MiniBoss02" },
                        code = "i_special_room_current_source_exclusion",
                    },
                    {
                        kind = "RequiredOfferedPeer",
                        phase = "room.generate_next",
                        roomSetKey = "I",
                        code = "i_reprieve_requires_i_peer",
                    },
                },
                code = "i_reprieve_eligibility",
            },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "I_Story01",
            kind = "Story",
            templateKey = "Story",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" } },
            rewardSurfaceKey = "FixedStory",
            encounterProfileKey = "Story",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                phase = "room.generate_next",
                requirements = {
                    {
                        kind = "CounterRange",
                        phase = "room.generate_next",
                        axis = "biomeDepthCache",
                        range = { min = 2 },
                        code = "i_story_too_early",
                    },
                    {
                        kind = "CurrentRoomCreationExclusion",
                        phase = "room.generate_next",
                        roomKeys = { "I_Story01", "I_Reprieve01", "I_MiniBoss01", "I_MiniBoss02" },
                        code = "i_special_room_current_source_exclusion",
                    },
                    {
                        kind = "RequiredOfferedPeer",
                        phase = "room.generate_next",
                        roomSetKey = "I",
                        code = "i_story_requires_i_peer",
                    },
                },
                code = "i_story_eligibility",
            },
            force = { axis = "biomeDepthCache", deadline = 4, kind = "depthWindow", start = 2 },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "I_MiniBoss01",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" },
                { index = 2, targetMode = "generated", type = "CWTartarusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressBoonOnly",
            encounterProfileKey = "I_MiniBoss01",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                phase = "room.generate_next",
                requirements = {
                    {
                        kind = "CounterRange",
                        phase = "room.generate_next",
                        axis = "biomeDepthCache",
                        range = { min = 3 },
                        code = "i_miniboss01_too_early",
                    },
                    {
                        kind = "RoomEnteredCount",
                        phase = "room.generate_next",
                        roomKeys = { "I_MiniBoss02" },
                        comparison = "==",
                        value = 0,
                        code = "i_miniboss01_other_miniboss_entered",
                    },
                    {
                        kind = "RequiredOfferedPeer",
                        phase = "room.generate_next",
                        roomSetKey = "I",
                        code = "i_miniboss01_requires_i_peer",
                    },
                    {
                        kind = "CurrentRoomCreationExclusion",
                        phase = "room.generate_next",
                        roomKeys = { "I_Story01", "I_Reprieve01", "I_MiniBoss01", "I_MiniBoss02" },
                        code = "i_special_room_current_source_exclusion",
                    },
                },
                code = "i_miniboss01_eligibility",
            },
            force = { axis = "biomeDepthCache", deadline = 7, kind = "depthWindow", start = 3 },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "I_MiniBoss02",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" },
                { index = 2, targetMode = "generated", type = "CWTartarusExitDoor" },
            },
            rewardSurfaceKey = "RunProgressBoonOnly",
            encounterProfileKey = "I_MiniBoss02",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                phase = "room.generate_next",
                requirements = {
                    {
                        kind = "CounterRange",
                        phase = "room.generate_next",
                        axis = "biomeDepthCache",
                        range = { min = 3 },
                        code = "i_miniboss02_too_early",
                    },
                    {
                        kind = "RoomEnteredCount",
                        phase = "room.generate_next",
                        roomKeys = { "I_MiniBoss01" },
                        comparison = "==",
                        value = 0,
                        code = "i_miniboss02_other_miniboss_entered",
                    },
                    {
                        kind = "RequiredOfferedPeer",
                        phase = "room.generate_next",
                        roomSetKey = "I",
                        code = "i_miniboss02_requires_i_peer",
                    },
                    {
                        kind = "CurrentRoomCreationExclusion",
                        phase = "room.generate_next",
                        roomKeys = { "I_Story01", "I_Reprieve01", "I_MiniBoss01", "I_MiniBoss02" },
                        code = "i_special_room_current_source_exclusion",
                    },
                    {
                        kind = "ClockworkCapacity",
                        phase = "room.generate_next",
                        counter = "nonGoalRewardsAcquired",
                        reserve = 1,
                        code = "i_miniboss02_requires_non_goal_capacity",
                    },
                },
                code = "i_miniboss02_eligibility",
            },
            force = { axis = "biomeDepthCache", deadline = 7, kind = "depthWindow", start = 3 },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "I_PreBoss01",
            kind = "Preboss",
            templateKey = "Preboss",
            tags = {},
            exits = { { index = 1, targetMode = "fixedBoss", type = "CWTartarusExitDoor" } },
            rewardSurfaceKey = "TartarusShop",
            encounterProfileKey = "Preboss",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsPerRoom = 1 },
            eligibility = {
                kind = "ClockworkGoalsRemaining",
                phase = "room.generate_next",
                comparison = "==",
                value = 0,
                code = "i_preboss01_goals_remaining",
            },
            force = {
                kind = "requirement",
                requirement = {
                    kind = "ClockworkNonGoalLimitReached",
                    phase = "room.generate_next",
                    code = "i_preboss01_non_goal_limit",
                },
            },
            terminal = true,
            fixed = true,
            localChildren = {},
        },
        {
            key = "I_PreBoss02",
            kind = "Preboss",
            templateKey = "Preboss",
            tags = {},
            exits = { { index = 1, targetMode = "fixedBoss", type = "CWTartarusExitDoor" } },
            rewardSurfaceKey = "TartarusShop",
            encounterProfileKey = "Preboss",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsPerRoom = 1 },
            eligibility = {
                kind = "ClockworkGoalsRemaining",
                phase = "room.generate_next",
                comparison = "==",
                value = 0,
                code = "i_preboss02_goals_remaining",
            },
            force = {
                kind = "requirement",
                requirement = {
                    kind = "ClockworkNonGoalLimitReached",
                    phase = "room.generate_next",
                    code = "i_preboss02_non_goal_limit",
                },
            },
            terminal = true,
            fixed = true,
            localChildren = {},
        },
    },
    canonicalCapacity = {
        {
            candidateConstraints = { templateKey = "ClockworkCombat" },
            contexts = {
                { biomeDepthCache = 1, count = 2 },
                { biomeDepthCache = 2, count = 2 },
                { biomeDepthCache = 3, count = 2 },
                { biomeDepthCache = 4, count = 2 },
                { biomeDepthCache = 5, count = 2 },
                { biomeDepthCache = 6, count = 2 },
                { biomeDepthCache = 7, count = 2 },
                { biomeDepthCache = 8, count = 2 },
                { biomeDepthCache = 9, count = 2 },
                { biomeDepthCache = 10, count = 2 },
                { biomeDepthCache = 11, count = 2 },
            },
            familyKey = "I_ClockworkCombat",
        },
    },
}
