return {
    key = "I",
    label = "Tartarus",
    routeKey = "Underworld",
    biomeStepKey = "Underworld_I",
    layout = {
        kind = "LinearBiome",
        start = { mode = "fixed", roomKeys = { "I_Intro" } },
        continuation = { defaultBatchRuleKey = "ClockworkDoorBatch", overrides = {} },
        terminal = {
            roomKey = "I_PreBoss02",
            transitionRuleKey = "PrebossEntry",
            exitPolicy = {
                kind = "terminalWithCompanions",
                companionBatchRuleKey = "ClockworkDoorBatch",
            },
        },
        bounds = { maxBatches = 12, maxTargets = 24 },
    },
    biomeState = {
        initialGoals = { authored = false, value = 5 },
        maxNonGoalRewards = { authored = true, values = { 3, 4, 5, 6 } },
    },
    rooms = {
        {
            key = "I_Intro",
            label = "Entrance",
            kind = "Intro",
            templateKey = "FixedIntro",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" } },
            incomingReward = { kind = "none" },
            encounterProfileKey = "FixedIntro",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            force = { axis = "biomeDepthCache", deadline = 1, kind = "depthWindow", start = 0 },
            localChildren = {},
        },
        {
            key = "I_Combat01",
            label = "Combat 01",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" },
                { index = 2, targetMode = "generated", type = "CWTartarusExitDoor" },
            },
            incomingReward = {
                kind = "incomingKind",
                kinds = {
                    {
                        key = "Goal",
                        reward = { kind = "fixed", rewardType = "ClockworkGoal", constraints = {} },
                    },
                    {
                        key = "NonGoal",
                        reward = {
                            kind = "countedChoice",
                            storeKeys = { "TartarusRewards" },
                            eligibleRewardTypes = {},
                            ineligibleRewardTypes = { "Boon" },
                        },
                    },
                },
            },
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "ClockworkCapacity",
                counter = "nonGoalRewardsAcquired",
                reserve = 1,
                code = "clockwork_extension_capacity_exhausted",
            },
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat02",
            label = "Combat 02",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" } },
            incomingReward = {
                kind = "incomingKind",
                kinds = {
                    {
                        key = "Goal",
                        reward = { kind = "fixed", rewardType = "ClockworkGoal", constraints = {} },
                    },
                    {
                        key = "NonGoal",
                        reward = {
                            kind = "countedChoice",
                            storeKeys = { "TartarusRewards" },
                            eligibleRewardTypes = {},
                            ineligibleRewardTypes = { "Boon" },
                        },
                    },
                },
            },
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat03",
            label = "Combat 03",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" },
                { index = 2, targetMode = "generated", type = "CWTartarusExitDoor" },
            },
            incomingReward = {
                kind = "incomingKind",
                kinds = {
                    {
                        key = "Goal",
                        reward = { kind = "fixed", rewardType = "ClockworkGoal", constraints = {} },
                    },
                    {
                        key = "NonGoal",
                        reward = {
                            kind = "countedChoice",
                            storeKeys = { "TartarusRewards" },
                            eligibleRewardTypes = {},
                            ineligibleRewardTypes = { "Boon" },
                        },
                    },
                },
            },
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "ClockworkCapacity",
                counter = "nonGoalRewardsAcquired",
                reserve = 1,
                code = "clockwork_extension_capacity_exhausted",
            },
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat04",
            label = "Combat 04",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" },
                { index = 2, targetMode = "generated", type = "CWTartarusExitDoor" },
            },
            incomingReward = {
                kind = "incomingKind",
                kinds = {
                    {
                        key = "Goal",
                        reward = { kind = "fixed", rewardType = "ClockworkGoal", constraints = {} },
                    },
                    {
                        key = "NonGoal",
                        reward = {
                            kind = "countedChoice",
                            storeKeys = { "TartarusRewards" },
                            eligibleRewardTypes = {},
                            ineligibleRewardTypes = { "Boon" },
                        },
                    },
                },
            },
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "ClockworkCapacity",
                counter = "nonGoalRewardsAcquired",
                reserve = 1,
                code = "clockwork_extension_capacity_exhausted",
            },
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat05",
            label = "Combat 05",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" } },
            incomingReward = {
                kind = "incomingKind",
                kinds = {
                    {
                        key = "Goal",
                        reward = { kind = "fixed", rewardType = "ClockworkGoal", constraints = {} },
                    },
                    {
                        key = "NonGoal",
                        reward = {
                            kind = "countedChoice",
                            storeKeys = { "TartarusRewards" },
                            eligibleRewardTypes = {},
                            ineligibleRewardTypes = { "Boon" },
                        },
                    },
                },
            },
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat06",
            label = "Combat 06",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" } },
            incomingReward = {
                kind = "incomingKind",
                kinds = {
                    {
                        key = "Goal",
                        reward = { kind = "fixed", rewardType = "ClockworkGoal", constraints = {} },
                    },
                    {
                        key = "NonGoal",
                        reward = {
                            kind = "countedChoice",
                            storeKeys = { "TartarusRewards" },
                            eligibleRewardTypes = {},
                            ineligibleRewardTypes = { "Boon" },
                        },
                    },
                },
            },
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat07",
            label = "Combat 07",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" } },
            incomingReward = {
                kind = "incomingKind",
                kinds = {
                    {
                        key = "Goal",
                        reward = { kind = "fixed", rewardType = "ClockworkGoal", constraints = {} },
                    },
                    {
                        key = "NonGoal",
                        reward = {
                            kind = "countedChoice",
                            storeKeys = { "TartarusRewards" },
                            eligibleRewardTypes = {},
                            ineligibleRewardTypes = { "Boon" },
                        },
                    },
                },
            },
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat08",
            label = "Combat 08",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" } },
            incomingReward = {
                kind = "incomingKind",
                kinds = {
                    {
                        key = "Goal",
                        reward = { kind = "fixed", rewardType = "ClockworkGoal", constraints = {} },
                    },
                    {
                        key = "NonGoal",
                        reward = {
                            kind = "countedChoice",
                            storeKeys = { "TartarusRewards" },
                            eligibleRewardTypes = {},
                            ineligibleRewardTypes = { "Boon" },
                        },
                    },
                },
            },
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat09",
            label = "Combat 09",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" },
                { index = 2, targetMode = "generated", type = "CWTartarusExitDoor" },
            },
            incomingReward = {
                kind = "incomingKind",
                kinds = {
                    {
                        key = "Goal",
                        reward = { kind = "fixed", rewardType = "ClockworkGoal", constraints = {} },
                    },
                    {
                        key = "NonGoal",
                        reward = {
                            kind = "countedChoice",
                            storeKeys = { "TartarusRewards" },
                            eligibleRewardTypes = {},
                            ineligibleRewardTypes = { "Boon" },
                        },
                    },
                },
            },
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "ClockworkCapacity",
                counter = "nonGoalRewardsAcquired",
                reserve = 1,
                code = "clockwork_extension_capacity_exhausted",
            },
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat10",
            label = "Combat 10",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" },
                { index = 2, targetMode = "generated", type = "CWTartarusExitDoor" },
            },
            incomingReward = {
                kind = "incomingKind",
                kinds = {
                    {
                        key = "Goal",
                        reward = { kind = "fixed", rewardType = "ClockworkGoal", constraints = {} },
                    },
                    {
                        key = "NonGoal",
                        reward = {
                            kind = "countedChoice",
                            storeKeys = { "TartarusRewards" },
                            eligibleRewardTypes = {},
                            ineligibleRewardTypes = { "Boon" },
                        },
                    },
                },
            },
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "ClockworkCapacity",
                counter = "nonGoalRewardsAcquired",
                reserve = 1,
                code = "clockwork_extension_capacity_exhausted",
            },
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat11",
            label = "Combat 11",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" },
                { index = 2, targetMode = "generated", type = "CWTartarusExitDoor" },
            },
            incomingReward = {
                kind = "incomingKind",
                kinds = {
                    {
                        key = "Goal",
                        reward = { kind = "fixed", rewardType = "ClockworkGoal", constraints = {} },
                    },
                    {
                        key = "NonGoal",
                        reward = {
                            kind = "countedChoice",
                            storeKeys = { "TartarusRewards" },
                            eligibleRewardTypes = {},
                            ineligibleRewardTypes = { "Boon" },
                        },
                    },
                },
            },
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "ClockworkCapacity",
                counter = "nonGoalRewardsAcquired",
                reserve = 1,
                code = "clockwork_extension_capacity_exhausted",
            },
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat12",
            label = "Combat 12",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" },
                { index = 2, targetMode = "generated", type = "CWTartarusExitDoor" },
            },
            incomingReward = {
                kind = "incomingKind",
                kinds = {
                    {
                        key = "Goal",
                        reward = { kind = "fixed", rewardType = "ClockworkGoal", constraints = {} },
                    },
                    {
                        key = "NonGoal",
                        reward = {
                            kind = "countedChoice",
                            storeKeys = { "TartarusRewards" },
                            eligibleRewardTypes = {},
                            ineligibleRewardTypes = { "Boon" },
                        },
                    },
                },
            },
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "ClockworkCapacity",
                counter = "nonGoalRewardsAcquired",
                reserve = 1,
                code = "clockwork_extension_capacity_exhausted",
            },
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat13",
            label = "Combat 13",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" } },
            incomingReward = {
                kind = "incomingKind",
                kinds = {
                    {
                        key = "Goal",
                        reward = { kind = "fixed", rewardType = "ClockworkGoal", constraints = {} },
                    },
                    {
                        key = "NonGoal",
                        reward = {
                            kind = "countedChoice",
                            storeKeys = { "TartarusRewards" },
                            eligibleRewardTypes = {},
                            ineligibleRewardTypes = { "Boon" },
                        },
                    },
                },
            },
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat14",
            label = "Combat 14",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" } },
            incomingReward = {
                kind = "incomingKind",
                kinds = {
                    {
                        key = "Goal",
                        reward = { kind = "fixed", rewardType = "ClockworkGoal", constraints = {} },
                    },
                    {
                        key = "NonGoal",
                        reward = {
                            kind = "countedChoice",
                            storeKeys = { "TartarusRewards" },
                            eligibleRewardTypes = {},
                            ineligibleRewardTypes = { "Boon" },
                        },
                    },
                },
            },
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat15",
            label = "Combat 15",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" },
                { index = 2, targetMode = "generated", type = "CWTartarusExitDoor" },
            },
            incomingReward = {
                kind = "incomingKind",
                kinds = {
                    {
                        key = "Goal",
                        reward = { kind = "fixed", rewardType = "ClockworkGoal", constraints = {} },
                    },
                    {
                        key = "NonGoal",
                        reward = {
                            kind = "countedChoice",
                            storeKeys = { "TartarusRewards" },
                            eligibleRewardTypes = {},
                            ineligibleRewardTypes = { "Boon" },
                        },
                    },
                },
            },
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "ClockworkCapacity",
                counter = "nonGoalRewardsAcquired",
                reserve = 1,
                code = "clockwork_extension_capacity_exhausted",
            },
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat16",
            label = "Combat 16",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" } },
            incomingReward = {
                kind = "incomingKind",
                kinds = {
                    {
                        key = "Goal",
                        reward = { kind = "fixed", rewardType = "ClockworkGoal", constraints = {} },
                    },
                    {
                        key = "NonGoal",
                        reward = {
                            kind = "countedChoice",
                            storeKeys = { "TartarusRewards" },
                            eligibleRewardTypes = {},
                            ineligibleRewardTypes = { "Boon" },
                        },
                    },
                },
            },
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat17",
            label = "Combat 17",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" } },
            incomingReward = {
                kind = "incomingKind",
                kinds = {
                    {
                        key = "Goal",
                        reward = { kind = "fixed", rewardType = "ClockworkGoal", constraints = {} },
                    },
                    {
                        key = "NonGoal",
                        reward = {
                            kind = "countedChoice",
                            storeKeys = { "TartarusRewards" },
                            eligibleRewardTypes = {},
                            ineligibleRewardTypes = { "Boon" },
                        },
                    },
                },
            },
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat18",
            label = "Combat 18",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" },
                { index = 2, targetMode = "generated", type = "CWTartarusExitDoor" },
            },
            incomingReward = {
                kind = "incomingKind",
                kinds = {
                    {
                        key = "Goal",
                        reward = { kind = "fixed", rewardType = "ClockworkGoal", constraints = {} },
                    },
                    {
                        key = "NonGoal",
                        reward = {
                            kind = "countedChoice",
                            storeKeys = { "TartarusRewards" },
                            eligibleRewardTypes = {},
                            ineligibleRewardTypes = { "Boon" },
                        },
                    },
                },
            },
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "ClockworkCapacity",
                counter = "nonGoalRewardsAcquired",
                reserve = 1,
                code = "clockwork_extension_capacity_exhausted",
            },
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat19",
            label = "Combat 19",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" } },
            incomingReward = {
                kind = "incomingKind",
                kinds = {
                    {
                        key = "Goal",
                        reward = { kind = "fixed", rewardType = "ClockworkGoal", constraints = {} },
                    },
                    {
                        key = "NonGoal",
                        reward = {
                            kind = "countedChoice",
                            storeKeys = { "TartarusRewards" },
                            eligibleRewardTypes = {},
                            ineligibleRewardTypes = { "Boon" },
                        },
                    },
                },
            },
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat20",
            label = "Combat 20",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" } },
            incomingReward = {
                kind = "incomingKind",
                kinds = {
                    {
                        key = "Goal",
                        reward = { kind = "fixed", rewardType = "ClockworkGoal", constraints = {} },
                    },
                    {
                        key = "NonGoal",
                        reward = {
                            kind = "countedChoice",
                            storeKeys = { "TartarusRewards" },
                            eligibleRewardTypes = {},
                            ineligibleRewardTypes = { "Boon" },
                        },
                    },
                },
            },
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat21",
            label = "Combat 21",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" },
                { index = 2, targetMode = "generated", type = "CWTartarusExitDoor" },
            },
            incomingReward = {
                kind = "incomingKind",
                kinds = {
                    {
                        key = "Goal",
                        reward = { kind = "fixed", rewardType = "ClockworkGoal", constraints = {} },
                    },
                    {
                        key = "NonGoal",
                        reward = {
                            kind = "countedChoice",
                            storeKeys = { "TartarusRewards" },
                            eligibleRewardTypes = {},
                            ineligibleRewardTypes = { "Boon" },
                        },
                    },
                },
            },
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "ClockworkCapacity",
                counter = "nonGoalRewardsAcquired",
                reserve = 1,
                code = "clockwork_extension_capacity_exhausted",
            },
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat22",
            label = "Combat 22",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" },
                { index = 2, targetMode = "generated", type = "CWTartarusExitDoor" },
            },
            incomingReward = {
                kind = "incomingKind",
                kinds = {
                    {
                        key = "Goal",
                        reward = { kind = "fixed", rewardType = "ClockworkGoal", constraints = {} },
                    },
                    {
                        key = "NonGoal",
                        reward = {
                            kind = "countedChoice",
                            storeKeys = { "TartarusRewards" },
                            eligibleRewardTypes = {},
                            ineligibleRewardTypes = { "Boon" },
                        },
                    },
                },
            },
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "ClockworkCapacity",
                counter = "nonGoalRewardsAcquired",
                reserve = 1,
                code = "clockwork_extension_capacity_exhausted",
            },
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat23",
            label = "Combat 23",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" } },
            incomingReward = {
                kind = "incomingKind",
                kinds = {
                    {
                        key = "Goal",
                        reward = { kind = "fixed", rewardType = "ClockworkGoal", constraints = {} },
                    },
                    {
                        key = "NonGoal",
                        reward = {
                            kind = "countedChoice",
                            storeKeys = { "TartarusRewards" },
                            eligibleRewardTypes = {},
                            ineligibleRewardTypes = { "Boon" },
                        },
                    },
                },
            },
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Combat24",
            label = "Combat 24",
            kind = "Combat",
            templateKey = "ClockworkCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" } },
            incomingReward = {
                kind = "incomingKind",
                kinds = {
                    {
                        key = "Goal",
                        reward = { kind = "fixed", rewardType = "ClockworkGoal", constraints = {} },
                    },
                    {
                        key = "NonGoal",
                        reward = {
                            kind = "countedChoice",
                            storeKeys = { "TartarusRewards" },
                            eligibleRewardTypes = {},
                            ineligibleRewardTypes = { "Boon" },
                        },
                    },
                },
            },
            encounterProfileKey = "ClockworkCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { max = 5 },
                code = "biome_depth_out_of_range",
            },
            canonicalFamily = "I_ClockworkCombat",
            localChildren = {},
        },
        {
            key = "I_Reprieve01",
            label = "Fountain",
            kind = "Reprieve",
            templateKey = "Fountain",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" },
                { index = 2, targetMode = "generated", type = "CWTartarusExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "TartarusRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "HealthRestore",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { min = 4 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "CurrentRoomCreationExclusion",
                        roomKeys = { "I_Story01", "I_Reprieve01", "I_MiniBoss01", "I_MiniBoss02" },
                        code = "current_room_creation_excluded",
                    },
                    {
                        kind = "RequiredOfferedPeer",
                        roomSetKey = "I",
                        code = "required_peer_not_offered",
                    },
                },
            },
            localChildren = {},
        },
        {
            key = "I_Story01",
            label = "Hades",
            kind = "Story",
            templateKey = "Story",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" } },
            incomingReward = { kind = "fixed", rewardType = "Story", constraints = {} },
            encounterProfileKey = "Story",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { min = 2 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "CurrentRoomCreationExclusion",
                        roomKeys = { "I_Story01", "I_Reprieve01", "I_MiniBoss01", "I_MiniBoss02" },
                        code = "current_room_creation_excluded",
                    },
                    {
                        kind = "RequiredOfferedPeer",
                        roomSetKey = "I",
                        code = "required_peer_not_offered",
                    },
                },
            },
            force = { axis = "biomeDepthCache", deadline = 4, kind = "depthWindow", start = 2 },
            localChildren = {},
        },
        {
            key = "I_MiniBoss01",
            label = "The Verminancer",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" },
                { index = 2, targetMode = "generated", type = "CWTartarusExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "TartarusRewards" }, eligibleRewardTypes = { "Boon" }, ineligibleRewardTypes = {} },
            encounterProfileKey = "I_MiniBoss01",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { min = 3 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RoomEnteredCount",
                        roomKeys = { "I_MiniBoss02" },
                        comparison = "==",
                        value = 0,
                        code = "other_miniboss_entered",
                    },
                    {
                        kind = "RequiredOfferedPeer",
                        roomSetKey = "I",
                        code = "required_peer_not_offered",
                    },
                    {
                        kind = "CurrentRoomCreationExclusion",
                        roomKeys = { "I_Story01", "I_Reprieve01", "I_MiniBoss01", "I_MiniBoss02" },
                        code = "current_room_creation_excluded",
                    },
                },
            },
            force = { axis = "biomeDepthCache", deadline = 7, kind = "depthWindow", start = 3 },
            localChildren = {},
        },
        {
            key = "I_MiniBoss02",
            label = "Goldwrath",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "CWTartarusExitDoor" },
                { index = 2, targetMode = "generated", type = "CWTartarusExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "TartarusRewards" }, eligibleRewardTypes = { "Boon" }, ineligibleRewardTypes = {} },
            encounterProfileKey = "I_MiniBoss02",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { min = 3 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RoomEnteredCount",
                        roomKeys = { "I_MiniBoss01" },
                        comparison = "==",
                        value = 0,
                        code = "other_miniboss_entered",
                    },
                    {
                        kind = "RequiredOfferedPeer",
                        roomSetKey = "I",
                        code = "required_peer_not_offered",
                    },
                    {
                        kind = "CurrentRoomCreationExclusion",
                        roomKeys = { "I_Story01", "I_Reprieve01", "I_MiniBoss01", "I_MiniBoss02" },
                        code = "current_room_creation_excluded",
                    },
                    {
                        kind = "ClockworkCapacity",
                        counter = "nonGoalRewardsAcquired",
                        reserve = 1,
                        code = "clockwork_non_goal_capacity_exhausted",
                    },
                },
            },
            force = { axis = "biomeDepthCache", deadline = 7, kind = "depthWindow", start = 3 },
            localChildren = {},
        },
        {
            key = "I_PreBoss02",
            label = "Preboss",
            kind = "Preboss",
            templateKey = "DirectPreboss",
            tags = {},
            exits = { { index = 1, targetMode = "fixedBoss", type = "CWTartarusExitDoor" } },
            incomingReward = { kind = "shop", shopProfileKey = "I_WorldShop" },
            entryOfferPolicy = { kind = "shopOnly" },
            encounterProfileKey = "Preboss",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsPerRoom = 1 },
            eligibility = {
                kind = "ClockworkGoalsRemaining",
                comparison = "==",
                value = 0,
                code = "clockwork_goals_remaining",
            },
            force = {
                kind = "requirement",
                requirement = {
                    kind = "ClockworkNonGoalLimitReached",
                    code = "clockwork_non_goal_limit_not_reached",
                },
            },
            localChildren = {},
        },
    },
    canonicalCapacity = {
        {
            candidateConstraints = { templateKey = "ClockworkCombat" },
            contexts = {
                { biomeDepthCache = 1, count = 2 },
                { biomeDepthCache = 2, count = 2 },
                { biomeDepthCache = 3, count = 2 },
                { biomeDepthCache = 4, count = 2 },
                { biomeDepthCache = 5, count = 2 },
                { biomeDepthCache = 6, count = 2 },
                { biomeDepthCache = 7, count = 2 },
                { biomeDepthCache = 8, count = 2 },
                { biomeDepthCache = 9, count = 2 },
                { biomeDepthCache = 10, count = 2 },
                { biomeDepthCache = 11, count = 2 },
            },
            familyKey = "I_ClockworkCombat",
        },
    },
}
