return {
    key = "N",
    label = "Ephyra",
    routeKey = "Surface",
    biomeStepKey = "Surface_N",
    layout = {
        kind = "HubBiome",
        entry = {
            mode = "fixedSequence",
            roomKeys = { "N_Opening01", "N_PreHub01", "N_Hub" },
        },
        hub = {
            roomKey = "N_Hub",
            batchRuleKey = "EphyraHubBatch",
            doorCountStateKey = "hubDoorCount",
            visitedTargetCount = 6,
        },
        terminal = {
            roomKey = "N_PreBoss01",
            transitionRuleKey = "PrebossEntry",
            exitPolicy = { kind = "singleTerminal" },
        },
        bounds = { maxBatches = 1, maxTargets = 10 },
    },
    combatAppearancePolicy = "physicalHubDoorUnique",
    biomeState = {
        hubDoorCount = { authored = true, values = { 9, 10 } },
        visitedTargetCount = { authored = false, value = 6 },
    },
    rooms = {
        {
            key = "N_Opening01",
            kind = "Opening",
            templateKey = "FixedOpening",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "N_OpeningDoor" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress" }, eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion", "RoomMoneyDrop", "MaxHealthDrop", "MaxManaDrop" } },
            encounterProfileKey = "N_Opening",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            localChildren = {},
        },
        {
            key = "N_PreHub01",
            kind = "PreHub",
            templateKey = "FixedPreHub",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "EphyraExitDoorReturn" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress" }, eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion", "RoomMoneyDrop", "MaxHealthDrop", "MaxManaDrop" } },
            encounterProfileKey = "FixedPreHub",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = {},
            localChildren = {},
        },
        {
            key = "N_Hub",
            kind = "Hub",
            templateKey = "EphyraHub",
            tags = {},
            exits = {},
            incomingReward = { kind = "none" },
            encounterProfileKey = "None",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 0 },
            caps = { maxAppearancesThisBiome = 1 },
            localChildren = {},
            metadata = { availableDoorCount = { max = 10, min = 9 }, physicalDoorKind = "EphyraExitDoor" },
        },
        {
            key = "N_Combat01",
            kind = "Combat",
            templateKey = "EphyraCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "EphyraExitDoorReturn" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "HubRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {}, batchConstraint = "NHubUniqueNonBoon" },
            encounterProfileKey = "EphyraCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = {},
            eligibility = {
                kind = "BiomeRoomCreatedAny",
                roomKeys = { "N_PreHub01" },
                code = "required_biome_room_not_created",
            },
            localChildren = {},
            metadata = { hubDoorId = 617113 },
        },
        {
            key = "N_Combat02",
            kind = "Combat",
            templateKey = "EphyraCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "EphyraExitDoorReturn" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "HubRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {}, batchConstraint = "NHubUniqueNonBoon" },
            encounterProfileKey = "EphyraCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = {},
            eligibility = {
                kind = "BiomeRoomCreatedAny",
                roomKeys = { "N_PreHub01" },
                code = "required_biome_room_not_created",
            },
            localChildren = {
                {
                    doorId = 558353,
                    gameRoomKey = "N_Sub01",
                    key = "sideDoor1",
                    kind = "sideRoom",
                    ordinal = 1,
                    reward = { kind = "countedChoice", storeKeys = { "SubRoomRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
                },
                {
                    doorId = 558352,
                    gameRoomKey = "N_Sub03",
                    key = "sideDoor2",
                    kind = "sideRoom",
                    ordinal = 2,
                    reward = { kind = "countedChoice", storeKeys = { "SubRoomRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
                },
            },
            metadata = { hubDoorId = 560725 },
        },
        {
            key = "N_Combat03",
            kind = "Combat",
            templateKey = "EphyraCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "EphyraExitDoorReturn" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "HubRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {}, batchConstraint = "NHubUniqueNonBoon" },
            encounterProfileKey = "EphyraCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = {},
            eligibility = {
                kind = "BiomeRoomCreatedAny",
                roomKeys = { "N_PreHub01" },
                code = "required_biome_room_not_created",
            },
            localChildren = {
                {
                    doorId = 558353,
                    gameRoomKey = "N_Sub04",
                    key = "sideDoor1",
                    kind = "sideRoom",
                    ordinal = 1,
                    reward = { kind = "countedChoice", storeKeys = { "SubRoomRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
                },
            },
            metadata = { hubDoorId = 560702 },
        },
        {
            key = "N_Combat04",
            kind = "Combat",
            templateKey = "EphyraCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "EphyraExitDoorReturn" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "HubRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {}, batchConstraint = "NHubUniqueNonBoon" },
            encounterProfileKey = "EphyraCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = {},
            eligibility = {
                kind = "BiomeRoomCreatedAny",
                roomKeys = { "N_PreHub01" },
                code = "required_biome_room_not_created",
            },
            localChildren = {
                {
                    doorId = 558834,
                    gameRoomKey = "N_Sub02",
                    key = "sideDoor1",
                    kind = "sideRoom",
                    ordinal = 1,
                    reward = { kind = "countedChoice", storeKeys = { "SubRoomRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
                },
                {
                    doorId = 558410,
                    gameRoomKey = "N_Sub06",
                    key = "sideDoor2",
                    kind = "sideRoom",
                    ordinal = 2,
                    reward = { kind = "countedChoice", storeKeys = { "SubRoomRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
                },
            },
            metadata = { hubDoorId = 560707 },
        },
        {
            key = "N_Combat05",
            kind = "Combat",
            templateKey = "EphyraCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "EphyraExitDoorReturn" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "HubRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {}, batchConstraint = "NHubUniqueNonBoon" },
            encounterProfileKey = "EphyraCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = {},
            eligibility = {
                kind = "BiomeRoomCreatedAny",
                roomKeys = { "N_PreHub01" },
                code = "required_biome_room_not_created",
            },
            localChildren = {
                {
                    doorId = 558354,
                    gameRoomKey = "N_Sub02",
                    key = "sideDoor1",
                    kind = "sideRoom",
                    ordinal = 1,
                    reward = { kind = "countedChoice", storeKeys = { "SubRoomRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
                },
                {
                    doorId = 558378,
                    gameRoomKey = "N_Sub07",
                    key = "sideDoor2",
                    kind = "sideRoom",
                    ordinal = 2,
                    reward = { kind = "countedChoice", storeKeys = { "SubRoomRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
                },
                {
                    doorId = 558379,
                    gameRoomKey = "N_Sub03",
                    key = "sideDoor3",
                    kind = "sideRoom",
                    ordinal = 3,
                    reward = { kind = "countedChoice", storeKeys = { "SubRoomRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
                },
            },
            metadata = { hubDoorId = 561337 },
        },
        {
            key = "N_Combat06",
            kind = "Combat",
            templateKey = "EphyraCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "EphyraExitDoorReturn" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "HubRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {}, batchConstraint = "NHubUniqueNonBoon" },
            encounterProfileKey = "EphyraCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = {},
            eligibility = {
                kind = "BiomeRoomCreatedAny",
                roomKeys = { "N_PreHub01" },
                code = "required_biome_room_not_created",
            },
            localChildren = {
                {
                    doorId = 558378,
                    gameRoomKey = "N_Sub10",
                    key = "sideDoor1",
                    kind = "sideRoom",
                    ordinal = 1,
                    reward = { kind = "countedChoice", storeKeys = { "SubRoomRewardsHard" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
                },
                {
                    doorId = 560794,
                    gameRoomKey = "N_Sub05",
                    key = "sideDoor2",
                    kind = "sideRoom",
                    ordinal = 2,
                    reward = { kind = "countedChoice", storeKeys = { "SubRoomRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
                },
            },
            metadata = { hubDoorId = 560708 },
        },
        {
            key = "N_Combat07",
            kind = "Combat",
            templateKey = "EphyraCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "EphyraExitDoorReturn" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "HubRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {}, batchConstraint = "NHubUniqueNonBoon" },
            encounterProfileKey = "EphyraCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = {},
            eligibility = {
                kind = "BiomeRoomCreatedAny",
                roomKeys = { "N_PreHub01" },
                code = "required_biome_room_not_created",
            },
            localChildren = {},
            metadata = { hubDoorId = 617138 },
        },
        {
            key = "N_Combat08",
            kind = "Combat",
            templateKey = "EphyraCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "EphyraExitDoorReturn" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "HubRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {}, batchConstraint = "NHubUniqueNonBoon" },
            encounterProfileKey = "EphyraCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = {},
            eligibility = {
                kind = "BiomeRoomCreatedAny",
                roomKeys = { "N_PreHub01" },
                code = "required_biome_room_not_created",
            },
            localChildren = {},
            metadata = { hubDoorId = 560699 },
        },
        {
            key = "N_Combat09",
            kind = "Combat",
            templateKey = "EphyraCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "EphyraExitDoorReturn" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "HubRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {}, batchConstraint = "NHubUniqueNonBoon" },
            encounterProfileKey = "EphyraCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = {},
            eligibility = {
                kind = "BiomeRoomCreatedAny",
                roomKeys = { "N_PreHub01" },
                code = "required_biome_room_not_created",
            },
            localChildren = {
                {
                    doorId = 566392,
                    gameRoomKey = "N_Sub11",
                    key = "sideDoor1",
                    kind = "sideRoom",
                    ordinal = 1,
                    reward = { kind = "countedChoice", storeKeys = { "SubRoomRewardsHard" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
                },
                {
                    doorId = 566536,
                    gameRoomKey = "N_Sub08",
                    key = "sideDoor2",
                    kind = "sideRoom",
                    ordinal = 2,
                    reward = { kind = "countedChoice", storeKeys = { "SubRoomRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
                },
                {
                    doorId = 566394,
                    gameRoomKey = "N_Sub14",
                    key = "sideDoor3",
                    kind = "sideRoom",
                    ordinal = 3,
                    reward = { kind = "countedChoice", storeKeys = { "SubRoomRewardsHard" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
                },
            },
            metadata = { hubDoorId = 617012 },
        },
        {
            key = "N_Combat10",
            kind = "Combat",
            templateKey = "EphyraCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "EphyraExitDoorReturn" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "HubRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {}, batchConstraint = "NHubUniqueNonBoon" },
            encounterProfileKey = "EphyraCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = {},
            eligibility = {
                kind = "BiomeRoomCreatedAny",
                roomKeys = { "N_PreHub01" },
                code = "required_biome_room_not_created",
            },
            localChildren = {
                {
                    doorId = 558352,
                    gameRoomKey = "N_Sub05",
                    key = "sideDoor1",
                    kind = "sideRoom",
                    ordinal = 1,
                    reward = { kind = "countedChoice", storeKeys = { "SubRoomRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
                },
                {
                    doorId = 567015,
                    gameRoomKey = "N_Sub09",
                    key = "sideDoor2",
                    kind = "sideRoom",
                    ordinal = 2,
                    reward = { kind = "countedChoice", storeKeys = { "SubRoomRewardsHard" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
                },
            },
            metadata = { hubDoorId = 617151 },
        },
        {
            key = "N_Combat11",
            kind = "Combat",
            templateKey = "EphyraCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "EphyraExitDoorReturn" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "HubRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {}, batchConstraint = "NHubUniqueNonBoon" },
            encounterProfileKey = "EphyraCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = {},
            eligibility = {
                kind = "BiomeRoomCreatedAny",
                roomKeys = { "N_PreHub01" },
                code = "required_biome_room_not_created",
            },
            localChildren = {
                {
                    doorId = 558352,
                    gameRoomKey = "N_Sub01",
                    key = "sideDoor1",
                    kind = "sideRoom",
                    ordinal = 1,
                    reward = { kind = "countedChoice", storeKeys = { "SubRoomRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
                },
            },
            metadata = { hubDoorId = 561449 },
        },
        {
            key = "N_Combat12",
            kind = "Combat",
            templateKey = "EphyraCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "EphyraExitDoorReturn" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "HubRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = { "WeaponUpgrade", "HermesUpgrade" }, batchConstraint = "NHubUniqueNonBoon" },
            encounterProfileKey = "EphyraCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = {},
            eligibility = {
                kind = "BiomeRoomCreatedAny",
                roomKeys = { "N_PreHub01" },
                code = "required_biome_room_not_created",
            },
            localChildren = {
                {
                    doorId = 558352,
                    gameRoomKey = "N_Sub09",
                    key = "sideDoor1",
                    kind = "sideRoom",
                    ordinal = 1,
                    reward = { kind = "countedChoice", storeKeys = { "SubRoomRewardsHard" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
                },
                {
                    doorId = 566544,
                    gameRoomKey = "N_Sub10",
                    key = "sideDoor2",
                    kind = "sideRoom",
                    ordinal = 2,
                    reward = { kind = "countedChoice", storeKeys = { "SubRoomRewardsHard" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
                },
                {
                    doorId = 566545,
                    gameRoomKey = "N_Sub07",
                    key = "sideDoor3",
                    kind = "sideRoom",
                    ordinal = 3,
                    reward = { kind = "countedChoice", storeKeys = { "SubRoomRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
                },
            },
            metadata = { hubDoorId = 561389 },
        },
        {
            key = "N_Combat13",
            kind = "Combat",
            templateKey = "EphyraCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "EphyraExitDoorReturn" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "HubRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {}, batchConstraint = "NHubUniqueNonBoon" },
            encounterProfileKey = "EphyraCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = {},
            eligibility = {
                kind = "BiomeRoomCreatedAny",
                roomKeys = { "N_PreHub01" },
                code = "required_biome_room_not_created",
            },
            localChildren = {},
            metadata = { hubDoorId = 616992 },
        },
        {
            key = "N_Combat14",
            kind = "Combat",
            templateKey = "EphyraCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "EphyraExitDoorReturn" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "HubRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {}, batchConstraint = "NHubUniqueNonBoon" },
            encounterProfileKey = "EphyraCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = {},
            eligibility = {
                kind = "BiomeRoomCreatedAny",
                roomKeys = { "N_PreHub01" },
                code = "required_biome_room_not_created",
            },
            localChildren = {},
            metadata = { hubDoorId = 561403 },
        },
        {
            key = "N_Combat15",
            kind = "Combat",
            templateKey = "EphyraCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "EphyraExitDoorReturn" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "HubRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {}, batchConstraint = "NHubUniqueNonBoon" },
            encounterProfileKey = "EphyraCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = {},
            eligibility = {
                kind = "BiomeRoomCreatedAny",
                roomKeys = { "N_PreHub01" },
                code = "required_biome_room_not_created",
            },
            localChildren = {
                {
                    doorId = 657623,
                    gameRoomKey = "N_Sub03",
                    key = "sideDoor1",
                    kind = "sideRoom",
                    ordinal = 1,
                    reward = { kind = "countedChoice", storeKeys = { "SubRoomRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
                },
            },
            metadata = { hubDoorId = 560705 },
        },
        {
            key = "N_Combat16",
            kind = "Combat",
            templateKey = "EphyraCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "EphyraExitDoorReturn" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "HubRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {}, batchConstraint = "NHubUniqueNonBoon" },
            encounterProfileKey = "EphyraCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = {},
            eligibility = {
                kind = "BiomeRoomCreatedAny",
                roomKeys = { "N_PreHub01" },
                code = "required_biome_room_not_created",
            },
            localChildren = {
                {
                    doorId = 558352,
                    gameRoomKey = "N_Sub04",
                    key = "sideDoor1",
                    kind = "sideRoom",
                    ordinal = 1,
                    reward = { kind = "countedChoice", storeKeys = { "SubRoomRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
                },
            },
            metadata = { hubDoorId = 561354 },
        },
        {
            key = "N_Combat17",
            kind = "Combat",
            templateKey = "EphyraCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "EphyraExitDoorReturn" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "HubRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = { "WeaponUpgrade", "HermesUpgrade" }, batchConstraint = "NHubUniqueNonBoon" },
            encounterProfileKey = "EphyraCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = {},
            eligibility = {
                kind = "BiomeRoomCreatedAny",
                roomKeys = { "N_PreHub01" },
                code = "required_biome_room_not_created",
            },
            localChildren = {
                {
                    doorId = 558352,
                    gameRoomKey = "N_Sub11",
                    key = "sideDoor1",
                    kind = "sideRoom",
                    ordinal = 1,
                    reward = { kind = "countedChoice", storeKeys = { "SubRoomRewardsHard" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
                },
            },
            metadata = { hubDoorId = 561424 },
        },
        {
            key = "N_Combat18",
            kind = "Combat",
            templateKey = "EphyraCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "EphyraExitDoorReturn" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "HubRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {}, batchConstraint = "NHubUniqueNonBoon" },
            encounterProfileKey = "EphyraCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = {},
            eligibility = {
                kind = "BiomeRoomCreatedAny",
                roomKeys = { "N_PreHub01" },
                code = "required_biome_room_not_created",
            },
            localChildren = {
                {
                    doorId = 658853,
                    gameRoomKey = "N_Sub12",
                    key = "sideDoor1",
                    kind = "sideRoom",
                    ordinal = 1,
                    reward = { kind = "countedChoice", storeKeys = { "SubRoomRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
                },
            },
            metadata = { hubDoorId = 561374 },
        },
        {
            key = "N_Combat19",
            kind = "Combat",
            templateKey = "EphyraCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "EphyraExitDoorReturn" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "HubRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {}, batchConstraint = "NHubUniqueNonBoon" },
            encounterProfileKey = "EphyraCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = {},
            eligibility = {
                kind = "BiomeRoomCreatedAny",
                roomKeys = { "N_PreHub01" },
                code = "required_biome_room_not_created",
            },
            localChildren = {},
            metadata = { hubDoorId = 560620 },
        },
        {
            key = "N_Combat20",
            kind = "Combat",
            templateKey = "EphyraCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "EphyraExitDoorReturn" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "HubRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {}, batchConstraint = "NHubUniqueNonBoon" },
            encounterProfileKey = "EphyraCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = {},
            eligibility = {
                kind = "BiomeRoomCreatedAny",
                roomKeys = { "N_PreHub01" },
                code = "required_biome_room_not_created",
            },
            localChildren = {
                {
                    doorId = 659508,
                    gameRoomKey = "N_Sub06",
                    key = "sideDoor1",
                    kind = "sideRoom",
                    ordinal = 1,
                    reward = { kind = "countedChoice", storeKeys = { "SubRoomRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
                },
            },
            metadata = { hubDoorId = 561418 },
        },
        {
            key = "N_Combat21",
            kind = "Combat",
            templateKey = "EphyraCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "EphyraExitDoorReturn" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "HubRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {}, batchConstraint = "NHubUniqueNonBoon" },
            encounterProfileKey = "EphyraCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = {},
            eligibility = {
                kind = "BiomeRoomCreatedAny",
                roomKeys = { "N_PreHub01" },
                code = "required_biome_room_not_created",
            },
            localChildren = {},
            metadata = { hubDoorId = 560713 },
        },
        {
            key = "N_Combat22",
            kind = "Combat",
            templateKey = "EphyraCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "EphyraExitDoorReturn" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "HubRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {}, batchConstraint = "NHubUniqueNonBoon" },
            encounterProfileKey = "EphyraCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = {},
            eligibility = {
                kind = "BiomeRoomCreatedAny",
                roomKeys = { "N_PreHub01" },
                code = "required_biome_room_not_created",
            },
            localChildren = {
                {
                    doorId = 558352,
                    gameRoomKey = "N_Sub14",
                    key = "sideDoor1",
                    kind = "sideRoom",
                    ordinal = 1,
                    reward = { kind = "countedChoice", storeKeys = { "SubRoomRewardsHard" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
                },
                {
                    doorId = 661338,
                    gameRoomKey = "N_Sub02",
                    key = "sideDoor2",
                    kind = "sideRoom",
                    ordinal = 2,
                    reward = { kind = "countedChoice", storeKeys = { "SubRoomRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
                },
            },
            metadata = { hubDoorId = 560776 },
        },
        {
            key = "N_Combat23",
            kind = "Combat",
            templateKey = "EphyraCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "EphyraExitDoorReturn" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "HubRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {}, batchConstraint = "NHubUniqueNonBoon" },
            encounterProfileKey = "EphyraCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = {},
            eligibility = {
                kind = "BiomeRoomCreatedAny",
                roomKeys = { "N_PreHub01" },
                code = "required_biome_room_not_created",
            },
            localChildren = {
                {
                    doorId = 755971,
                    gameRoomKey = "N_Sub12",
                    key = "sideDoor1",
                    kind = "sideRoom",
                    ordinal = 1,
                    reward = { kind = "countedChoice", storeKeys = { "SubRoomRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
                },
                {
                    doorId = 755184,
                    gameRoomKey = "N_Sub13",
                    key = "sideDoor2",
                    kind = "sideRoom",
                    ordinal = 2,
                    reward = { kind = "countedChoice", storeKeys = { "SubRoomRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
                },
                {
                    doorId = 755185,
                    gameRoomKey = "N_Sub15",
                    key = "sideDoor3",
                    kind = "sideRoom",
                    ordinal = 3,
                    reward = { kind = "countedChoice", storeKeys = { "SubRoomRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
                },
            },
            metadata = { hubDoorId = 561368 },
        },
        {
            key = "N_MiniBoss01",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "EphyraExitDoorReturn" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress" }, eligibleRewardTypes = { "Boon" }, ineligibleRewardTypes = {} },
            encounterProfileKey = "MiniBossSatyrCrossbow",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "BiomeRoomCreatedAny",
                roomKeys = { "N_PreHub01" },
                code = "required_biome_room_not_created",
            },
            localChildren = {},
            metadata = { hubDoorId = 617043 },
        },
        {
            key = "N_MiniBoss02",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "EphyraExitDoorReturn" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress" }, eligibleRewardTypes = { "Boon" }, ineligibleRewardTypes = {} },
            encounterProfileKey = "MiniBossBoar",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "BiomeRoomCreatedAny",
                roomKeys = { "N_PreHub01" },
                code = "required_biome_room_not_created",
            },
            localChildren = {},
            metadata = { hubDoorId = 560889 },
        },
        {
            key = "N_Story01",
            kind = "Story",
            templateKey = "Story",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "EphyraExitDoorReturn" } },
            incomingReward = { kind = "fixed", rewardType = "Story", constraints = {} },
            encounterProfileKey = "Story",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxCreationsThisRun = 1 },
            eligibility = {
                kind = "BiomeRoomCreatedAny",
                roomKeys = { "N_PreHub01" },
                code = "required_biome_room_not_created",
            },
            localChildren = {},
            metadata = { hubDoorId = 560848 },
        },
        {
            key = "N_PreBoss01",
            kind = "Preboss",
            templateKey = "DirectPreboss",
            tags = {},
            exits = { { index = 1, targetMode = "fixedBoss", type = "EphyraExitDoorReturn" } },
            incomingReward = { kind = "shop", shopProfileKey = "WorldShop" },
            entryOfferPolicy = { kind = "shopOnly" },
            encounterProfileKey = "Preboss",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = {},
            eligibility = {
                kind = "HubVisitsCompleted",
                comparison = "==",
                value = 6,
                code = "hub_visit_count_mismatch",
            },
            localChildren = {},
        },
    },
}
