return {
    key = "O",
    label = "Thessaly",
    routeKey = "Surface",
    biomeStepKey = "Surface_O",
    layout = {
        kind = "LinearBiome",
        start = { mode = "fixed", roomKeys = { "O_Intro" } },
        continuation = { defaultBatchRuleKey = "Standard", overrides = {} },
        terminal = {
            roomKey = "O_PreBoss01",
            transitionRuleKey = "PrebossEntry",
            exitPolicy = { kind = "singleTerminal" },
        },
        bounds = { maxBatches = 7, maxTargets = 7 },
    },
    rooms = {
        {
            key = "O_Intro",
            label = "Entrance",
            kind = "Intro",
            templateKey = "FixedIntro",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            incomingReward = { kind = "none" },
            encounterProfileKey = "FixedIntro",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { exact = 1 },
                code = "biome_depth_out_of_range",
            },
            force = { axis = "biomeDepthCache", deadline = 1, kind = "depthWindow", start = 0 },
            localChildren = {},
        },
        {
            key = "O_Combat01",
            label = "Combat 01",
            kind = "Combat",
            templateKey = "ShipCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            incomingReward = { kind = "none" },
            encounterProfileKey = "ShipCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "RecentEncounterPhaseCount",
                profileKey = "ShipCombat",
                phaseKey = "Intro",
                roomWindow = 3,
                comparison = "<",
                value = 3,
                code = "recent_encounter_phase_capacity_exhausted",
            },
            canonicalFamily = "O_ShipCombat",
            localChildren = {},
        },
        {
            key = "O_Combat02",
            label = "Combat 02",
            kind = "Combat",
            templateKey = "ShipCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            incomingReward = { kind = "none" },
            encounterProfileKey = "ShipCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "RecentEncounterPhaseCount",
                profileKey = "ShipCombat",
                phaseKey = "Intro",
                roomWindow = 3,
                comparison = "<",
                value = 3,
                code = "recent_encounter_phase_capacity_exhausted",
            },
            canonicalFamily = "O_ShipCombat",
            localChildren = {},
        },
        {
            key = "O_Combat03",
            label = "Combat 03",
            kind = "Combat",
            templateKey = "ShipCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            incomingReward = { kind = "none" },
            encounterProfileKey = "ShipCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "RecentEncounterPhaseCount",
                profileKey = "ShipCombat",
                phaseKey = "Intro",
                roomWindow = 3,
                comparison = "<",
                value = 3,
                code = "recent_encounter_phase_capacity_exhausted",
            },
            canonicalFamily = "O_ShipCombat",
            localChildren = {},
        },
        {
            key = "O_Combat04",
            label = "Combat 04",
            kind = "Combat",
            templateKey = "ShipCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            incomingReward = { kind = "none" },
            encounterProfileKey = "ShipCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { max = 3 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RecentEncounterPhaseCount",
                        profileKey = "ShipCombat",
                        phaseKey = "Intro",
                        roomWindow = 3,
                        comparison = "<",
                        value = 3,
                        code = "recent_encounter_phase_capacity_exhausted",
                    },
                },
            },
            canonicalFamily = "O_ShipCombat",
            localChildren = {},
        },
        {
            key = "O_Combat05",
            label = "Combat 05",
            kind = "Combat",
            templateKey = "ShipCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            incomingReward = { kind = "none" },
            encounterProfileKey = "ShipCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "RecentEncounterPhaseCount",
                profileKey = "ShipCombat",
                phaseKey = "Intro",
                roomWindow = 3,
                comparison = "<",
                value = 3,
                code = "recent_encounter_phase_capacity_exhausted",
            },
            canonicalFamily = "O_ShipCombat",
            localChildren = {},
        },
        {
            key = "O_Combat06",
            label = "Combat 06",
            kind = "Combat",
            templateKey = "ShipCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            incomingReward = { kind = "none" },
            encounterProfileKey = "ShipCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "RecentEncounterPhaseCount",
                profileKey = "ShipCombat",
                phaseKey = "Intro",
                roomWindow = 3,
                comparison = "<",
                value = 3,
                code = "recent_encounter_phase_capacity_exhausted",
            },
            canonicalFamily = "O_ShipCombat",
            localChildren = {},
        },
        {
            key = "O_Combat07",
            label = "Combat 07",
            kind = "Combat",
            templateKey = "ShipCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            incomingReward = { kind = "none" },
            encounterProfileKey = "ShipCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { max = 3 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RecentEncounterPhaseCount",
                        profileKey = "ShipCombat",
                        phaseKey = "Intro",
                        roomWindow = 3,
                        comparison = "<",
                        value = 3,
                        code = "recent_encounter_phase_capacity_exhausted",
                    },
                },
            },
            canonicalFamily = "O_ShipCombat",
            localChildren = {},
        },
        {
            key = "O_Combat08",
            label = "Combat 08",
            kind = "Combat",
            templateKey = "ShipCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            incomingReward = { kind = "none" },
            encounterProfileKey = "ShipCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "RecentEncounterPhaseCount",
                profileKey = "ShipCombat",
                phaseKey = "Intro",
                roomWindow = 3,
                comparison = "<",
                value = 3,
                code = "recent_encounter_phase_capacity_exhausted",
            },
            canonicalFamily = "O_ShipCombat",
            localChildren = {},
        },
        {
            key = "O_Combat09",
            label = "Combat 09",
            kind = "Combat",
            templateKey = "ShipCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            incomingReward = { kind = "none" },
            encounterProfileKey = "ShipCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "RecentEncounterPhaseCount",
                profileKey = "ShipCombat",
                phaseKey = "Intro",
                roomWindow = 3,
                comparison = "<",
                value = 3,
                code = "recent_encounter_phase_capacity_exhausted",
            },
            canonicalFamily = "O_ShipCombat",
            localChildren = {},
        },
        {
            key = "O_Combat10",
            label = "Combat 10",
            kind = "Combat",
            templateKey = "ShipCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            incomingReward = { kind = "none" },
            encounterProfileKey = "ShipCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "RecentEncounterPhaseCount",
                profileKey = "ShipCombat",
                phaseKey = "Intro",
                roomWindow = 3,
                comparison = "<",
                value = 3,
                code = "recent_encounter_phase_capacity_exhausted",
            },
            canonicalFamily = "O_ShipCombat",
            localChildren = {},
        },
        {
            key = "O_Combat11",
            label = "Combat 11",
            kind = "Combat",
            templateKey = "ShipCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            incomingReward = { kind = "none" },
            encounterProfileKey = "ShipCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { max = 3 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RecentEncounterPhaseCount",
                        profileKey = "ShipCombat",
                        phaseKey = "Intro",
                        roomWindow = 3,
                        comparison = "<",
                        value = 3,
                        code = "recent_encounter_phase_capacity_exhausted",
                    },
                },
            },
            canonicalFamily = "O_ShipCombat",
            localChildren = {},
        },
        {
            key = "O_Combat12",
            label = "Combat 12",
            kind = "Combat",
            templateKey = "ShipCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            incomingReward = { kind = "none" },
            encounterProfileKey = "ShipCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "RecentEncounterPhaseCount",
                profileKey = "ShipCombat",
                phaseKey = "Intro",
                roomWindow = 3,
                comparison = "<",
                value = 3,
                code = "recent_encounter_phase_capacity_exhausted",
            },
            canonicalFamily = "O_ShipCombat",
            localChildren = {},
        },
        {
            key = "O_Combat13",
            label = "Combat 13",
            kind = "Combat",
            templateKey = "ShipCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            incomingReward = { kind = "none" },
            encounterProfileKey = "ShipCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { min = 6 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RecentEncounterPhaseCount",
                        profileKey = "ShipCombat",
                        phaseKey = "Intro",
                        roomWindow = 3,
                        comparison = ">=",
                        value = 3,
                        code = "recent_encounter_phase_count_mismatch",
                    },
                },
            },
            canonicalFamily = "O_ShipCombat",
            localChildren = {},
        },
        {
            key = "O_Combat14",
            label = "Combat 14",
            kind = "Combat",
            templateKey = "ShipCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            incomingReward = { kind = "none" },
            encounterProfileKey = "ShipCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "RecentEncounterPhaseCount",
                profileKey = "ShipCombat",
                phaseKey = "Intro",
                roomWindow = 3,
                comparison = "<",
                value = 3,
                code = "recent_encounter_phase_capacity_exhausted",
            },
            canonicalFamily = "O_ShipCombat",
            localChildren = {},
        },
        {
            key = "O_Combat15",
            label = "Combat 15",
            kind = "Combat",
            templateKey = "ShipCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            incomingReward = { kind = "none" },
            encounterProfileKey = "ShipCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { max = 3 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RecentEncounterPhaseCount",
                        profileKey = "ShipCombat",
                        phaseKey = "Intro",
                        roomWindow = 3,
                        comparison = "<",
                        value = 3,
                        code = "recent_encounter_phase_capacity_exhausted",
                    },
                },
            },
            canonicalFamily = "O_ShipCombat",
            localChildren = {},
        },
        {
            key = "O_Story01",
            label = "Circe",
            kind = "Story",
            templateKey = "Story",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            incomingReward = { kind = "fixed", rewardType = "Story", constraints = {} },
            encounterProfileKey = "Story",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeEncounterDepth",
                        range = { minExclusive = 3 },
                        code = "biome_encounter_depth_out_of_range",
                    },
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { max = 5 },
                        code = "biome_depth_out_of_range",
                    },
                },
            },
            force = {
                kind = "requirement",
                requirement = {
                    kind = "All",
                    requirements = {
                        {
                            kind = "CounterRange",
                            axis = "biomeDepthCache",
                            range = { exact = 5 },
                            code = "biome_depth_exact_mismatch",
                        },
                        {
                            kind = "RoomEnteredCount",
                            roomKeys = { "O_Shop01", "O_Story01" },
                            comparison = "==",
                            value = 0,
                            code = "paired_special_room_already_entered",
                        },
                    },
                },
            },
            localChildren = {},
        },
        {
            key = "O_Reprieve01",
            label = "Fountain",
            kind = "Reprieve",
            templateKey = "Fountain",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "HealthRestore",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { max = 5, min = 3 },
                code = "biome_depth_out_of_range",
            },
            localChildren = {},
        },
        {
            key = "O_Shop01",
            label = "Midshop",
            kind = "Shop",
            templateKey = "Shop",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            incomingReward = { kind = "shop", shopProfileKey = "WorldShop" },
            encounterProfileKey = "Shop",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeEncounterDepth",
                        range = { minExclusive = 3 },
                        code = "biome_encounter_depth_out_of_range",
                    },
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { max = 5 },
                        code = "biome_depth_out_of_range",
                    },
                },
            },
            force = {
                kind = "requirement",
                requirement = {
                    kind = "All",
                    requirements = {
                        {
                            kind = "CounterRange",
                            axis = "biomeDepthCache",
                            range = { exact = 5 },
                            code = "biome_depth_exact_mismatch",
                        },
                        {
                            kind = "RoomEnteredCount",
                            roomKeys = { "O_Shop01", "O_Story01" },
                            comparison = "==",
                            value = 0,
                            code = "paired_special_room_already_entered",
                        },
                    },
                },
            },
            localChildren = {},
        },
        {
            key = "O_Devotion01",
            label = "Trial",
            kind = "Devotion",
            templateKey = "Devotion",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            incomingReward = { kind = "fixed", rewardType = "Devotion", constraints = { "DevotionPairDistinct" } },
            encounterProfileKey = "Devotion",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeEncounterDepth",
                        range = { min = 2 },
                        code = "biome_encounter_depth_out_of_range",
                    },
                    {
                        kind = "PriorDistinctLootSources",
                        sourceDomain = "OlympianGods",
                        comparison = ">=",
                        value = 2,
                        code = "distinct_loot_source_count_mismatch",
                    },
                },
            },
            localChildren = {},
        },
        {
            key = "O_MiniBoss01",
            label = "Charybdis",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress" }, eligibleRewardTypes = { "Boon" }, ineligibleRewardTypes = {} },
            encounterProfileKey = "O_MiniBoss01",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { max = 5, min = 3 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RoomEnteredCount",
                        roomKeys = { "O_MiniBoss02" },
                        comparison = "==",
                        value = 0,
                        code = "other_miniboss_entered",
                    },
                },
            },
            localChildren = {},
        },
        {
            key = "O_MiniBoss02",
            label = "The Yargonaut",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress" }, eligibleRewardTypes = { "Boon" }, ineligibleRewardTypes = {} },
            encounterProfileKey = "O_MiniBoss02",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { max = 5, min = 3 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RoomEnteredCount",
                        roomKeys = { "O_MiniBoss01" },
                        comparison = "==",
                        value = 0,
                        code = "other_miniboss_entered",
                    },
                },
            },
            localChildren = {},
        },
        {
            key = "O_PreBoss01",
            label = "Preboss",
            kind = "Preboss",
            templateKey = "DirectPreboss",
            tags = {},
            exits = { { index = 1, targetMode = "fixedBoss", type = "ShipsExitDoor" } },
            incomingReward = { kind = "shop", shopProfileKey = "WorldShop" },
            entryOfferPolicy = { kind = "shopOnly" },
            encounterProfileKey = "Preboss",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { min = 7 },
                code = "biome_depth_out_of_range",
            },
            force = { axis = "biomeDepthCache", deadline = 7, kind = "depthWindow", start = 7 },
            localChildren = {},
        },
    },
    canonicalCapacity = {
        {
            candidateConstraints = { templateKey = "ShipCombat" },
            contexts = {
                { biomeDepthCache = 1, count = 1 },
                { biomeDepthCache = 2, count = 1 },
                { biomeDepthCache = 3, count = 1 },
                { biomeDepthCache = 4, count = 1 },
                { biomeDepthCache = 5, count = 1 },
                { biomeDepthCache = 6, count = 1 },
            },
            familyKey = "O_ShipCombat",
        },
    },
}
