return {
    key = "O",
    label = "Thessaly",
    routeKey = "Surface",
    biomeStepKey = "Surface_O",
    root = { mode = "fixed", roomKeys = { "O_Intro" } },
    terminalRoomKeys = { "O_PreBoss01" },
    batchRuleKey = "Standard",
    topologyBounds = { maxBatches = 7, maxLocalChildrenPerRoom = 2, maxTargets = 7 },
    rooms = {
        {
            key = "O_Intro",
            kind = "Intro",
            templateKey = "FixedIntro",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            rewardSurfaceKey = "None",
            encounterProfileKey = "FixedIntro",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { exact = 1 },
                code = "biome_depth_out_of_range",
            },
            force = { axis = "biomeDepthCache", deadline = 1, kind = "depthWindow", start = 0 },
            terminal = false,
            fixed = true,
            localChildren = {},
        },
        {
            key = "O_Combat01",
            kind = "Combat",
            templateKey = "ShipCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            rewardSurfaceKey = "None",
            encounterProfileKey = "ShipCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "RecentEncounterPhaseCount",
                profileKey = "ShipCombat",
                phaseKey = "Intro",
                roomWindow = 3,
                comparison = "<",
                value = 3,
                code = "recent_encounter_phase_capacity_exhausted",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "O_ShipCombat",
            localChildren = {},
        },
        {
            key = "O_Combat02",
            kind = "Combat",
            templateKey = "ShipCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            rewardSurfaceKey = "None",
            encounterProfileKey = "ShipCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "RecentEncounterPhaseCount",
                profileKey = "ShipCombat",
                phaseKey = "Intro",
                roomWindow = 3,
                comparison = "<",
                value = 3,
                code = "recent_encounter_phase_capacity_exhausted",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "O_ShipCombat",
            localChildren = {},
        },
        {
            key = "O_Combat03",
            kind = "Combat",
            templateKey = "ShipCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            rewardSurfaceKey = "None",
            encounterProfileKey = "ShipCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "RecentEncounterPhaseCount",
                profileKey = "ShipCombat",
                phaseKey = "Intro",
                roomWindow = 3,
                comparison = "<",
                value = 3,
                code = "recent_encounter_phase_capacity_exhausted",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "O_ShipCombat",
            localChildren = {},
        },
        {
            key = "O_Combat04",
            kind = "Combat",
            templateKey = "ShipCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            rewardSurfaceKey = "None",
            encounterProfileKey = "ShipCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { max = 3 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RecentEncounterPhaseCount",
                        profileKey = "ShipCombat",
                        phaseKey = "Intro",
                        roomWindow = 3,
                        comparison = "<",
                        value = 3,
                        code = "recent_encounter_phase_capacity_exhausted",
                    },
                },
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "O_ShipCombat",
            localChildren = {},
        },
        {
            key = "O_Combat05",
            kind = "Combat",
            templateKey = "ShipCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            rewardSurfaceKey = "None",
            encounterProfileKey = "ShipCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "RecentEncounterPhaseCount",
                profileKey = "ShipCombat",
                phaseKey = "Intro",
                roomWindow = 3,
                comparison = "<",
                value = 3,
                code = "recent_encounter_phase_capacity_exhausted",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "O_ShipCombat",
            localChildren = {},
        },
        {
            key = "O_Combat06",
            kind = "Combat",
            templateKey = "ShipCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            rewardSurfaceKey = "None",
            encounterProfileKey = "ShipCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "RecentEncounterPhaseCount",
                profileKey = "ShipCombat",
                phaseKey = "Intro",
                roomWindow = 3,
                comparison = "<",
                value = 3,
                code = "recent_encounter_phase_capacity_exhausted",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "O_ShipCombat",
            localChildren = {},
        },
        {
            key = "O_Combat07",
            kind = "Combat",
            templateKey = "ShipCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            rewardSurfaceKey = "None",
            encounterProfileKey = "ShipCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { max = 3 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RecentEncounterPhaseCount",
                        profileKey = "ShipCombat",
                        phaseKey = "Intro",
                        roomWindow = 3,
                        comparison = "<",
                        value = 3,
                        code = "recent_encounter_phase_capacity_exhausted",
                    },
                },
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "O_ShipCombat",
            localChildren = {},
        },
        {
            key = "O_Combat08",
            kind = "Combat",
            templateKey = "ShipCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            rewardSurfaceKey = "None",
            encounterProfileKey = "ShipCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "RecentEncounterPhaseCount",
                profileKey = "ShipCombat",
                phaseKey = "Intro",
                roomWindow = 3,
                comparison = "<",
                value = 3,
                code = "recent_encounter_phase_capacity_exhausted",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "O_ShipCombat",
            localChildren = {},
        },
        {
            key = "O_Combat09",
            kind = "Combat",
            templateKey = "ShipCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            rewardSurfaceKey = "None",
            encounterProfileKey = "ShipCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "RecentEncounterPhaseCount",
                profileKey = "ShipCombat",
                phaseKey = "Intro",
                roomWindow = 3,
                comparison = "<",
                value = 3,
                code = "recent_encounter_phase_capacity_exhausted",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "O_ShipCombat",
            localChildren = {},
        },
        {
            key = "O_Combat10",
            kind = "Combat",
            templateKey = "ShipCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            rewardSurfaceKey = "None",
            encounterProfileKey = "ShipCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "RecentEncounterPhaseCount",
                profileKey = "ShipCombat",
                phaseKey = "Intro",
                roomWindow = 3,
                comparison = "<",
                value = 3,
                code = "recent_encounter_phase_capacity_exhausted",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "O_ShipCombat",
            localChildren = {},
        },
        {
            key = "O_Combat11",
            kind = "Combat",
            templateKey = "ShipCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            rewardSurfaceKey = "None",
            encounterProfileKey = "ShipCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { max = 3 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RecentEncounterPhaseCount",
                        profileKey = "ShipCombat",
                        phaseKey = "Intro",
                        roomWindow = 3,
                        comparison = "<",
                        value = 3,
                        code = "recent_encounter_phase_capacity_exhausted",
                    },
                },
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "O_ShipCombat",
            localChildren = {},
        },
        {
            key = "O_Combat12",
            kind = "Combat",
            templateKey = "ShipCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            rewardSurfaceKey = "None",
            encounterProfileKey = "ShipCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "RecentEncounterPhaseCount",
                profileKey = "ShipCombat",
                phaseKey = "Intro",
                roomWindow = 3,
                comparison = "<",
                value = 3,
                code = "recent_encounter_phase_capacity_exhausted",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "O_ShipCombat",
            localChildren = {},
        },
        {
            key = "O_Combat13",
            kind = "Combat",
            templateKey = "ShipCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            rewardSurfaceKey = "None",
            encounterProfileKey = "ShipCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { min = 6 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RecentEncounterPhaseCount",
                        profileKey = "ShipCombat",
                        phaseKey = "Intro",
                        roomWindow = 3,
                        comparison = ">=",
                        value = 3,
                        code = "recent_encounter_phase_count_mismatch",
                    },
                },
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "O_ShipCombat",
            localChildren = {},
        },
        {
            key = "O_Combat14",
            kind = "Combat",
            templateKey = "ShipCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            rewardSurfaceKey = "None",
            encounterProfileKey = "ShipCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "RecentEncounterPhaseCount",
                profileKey = "ShipCombat",
                phaseKey = "Intro",
                roomWindow = 3,
                comparison = "<",
                value = 3,
                code = "recent_encounter_phase_capacity_exhausted",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "O_ShipCombat",
            localChildren = {},
        },
        {
            key = "O_Combat15",
            kind = "Combat",
            templateKey = "ShipCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            rewardSurfaceKey = "None",
            encounterProfileKey = "ShipCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { max = 3 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RecentEncounterPhaseCount",
                        profileKey = "ShipCombat",
                        phaseKey = "Intro",
                        roomWindow = 3,
                        comparison = "<",
                        value = 3,
                        code = "recent_encounter_phase_capacity_exhausted",
                    },
                },
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "O_ShipCombat",
            localChildren = {},
        },
        {
            key = "O_Story01",
            kind = "Story",
            templateKey = "Story",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            rewardSurfaceKey = "FixedStory",
            encounterProfileKey = "Story",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeEncounterDepth",
                        range = { minExclusive = 3 },
                        code = "biome_encounter_depth_out_of_range",
                    },
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { max = 5 },
                        code = "biome_depth_out_of_range",
                    },
                },
            },
            force = {
                kind = "requirement",
                requirement = {
                    kind = "All",
                    requirements = {
                        {
                            kind = "CounterRange",
                            axis = "biomeDepthCache",
                            range = { exact = 5 },
                            code = "biome_depth_exact_mismatch",
                        },
                        {
                            kind = "RoomEnteredCount",
                            roomKeys = { "O_Shop01", "O_Story01" },
                            comparison = "==",
                            value = 0,
                            code = "paired_special_room_already_entered",
                        },
                    },
                },
            },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "O_Reprieve01",
            kind = "Reprieve",
            templateKey = "Fountain",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "HealthRestore",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { max = 5, min = 3 },
                code = "biome_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "O_Shop01",
            kind = "Shop",
            templateKey = "Shop",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            rewardSurfaceKey = "WorldShop",
            encounterProfileKey = "Shop",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeEncounterDepth",
                        range = { minExclusive = 3 },
                        code = "biome_encounter_depth_out_of_range",
                    },
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { max = 5 },
                        code = "biome_depth_out_of_range",
                    },
                },
            },
            force = {
                kind = "requirement",
                requirement = {
                    kind = "All",
                    requirements = {
                        {
                            kind = "CounterRange",
                            axis = "biomeDepthCache",
                            range = { exact = 5 },
                            code = "biome_depth_exact_mismatch",
                        },
                        {
                            kind = "RoomEnteredCount",
                            roomKeys = { "O_Shop01", "O_Story01" },
                            comparison = "==",
                            value = 0,
                            code = "paired_special_room_already_entered",
                        },
                    },
                },
            },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "O_Devotion01",
            kind = "Devotion",
            templateKey = "Devotion",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            rewardSurfaceKey = "ForcedDevotion",
            encounterProfileKey = "Devotion",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeEncounterDepth",
                        range = { min = 2 },
                        code = "biome_encounter_depth_out_of_range",
                    },
                    {
                        kind = "PriorDistinctLootSources",
                        sourceDomain = "OlympianGods",
                        comparison = ">=",
                        value = 2,
                        code = "distinct_loot_source_count_mismatch",
                    },
                },
            },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "O_MiniBoss01",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            rewardSurfaceKey = "RunProgressBoonOnly",
            encounterProfileKey = "O_MiniBoss01",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { max = 5, min = 3 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RoomEnteredCount",
                        roomKeys = { "O_MiniBoss02" },
                        comparison = "==",
                        value = 0,
                        code = "other_miniboss_entered",
                    },
                },
            },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "O_MiniBoss02",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "ShipsExitDoor" } },
            rewardSurfaceKey = "RunProgressBoonOnly",
            encounterProfileKey = "O_MiniBoss02",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { max = 5, min = 3 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RoomEnteredCount",
                        roomKeys = { "O_MiniBoss01" },
                        comparison = "==",
                        value = 0,
                        code = "other_miniboss_entered",
                    },
                },
            },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "O_PreBoss01",
            kind = "Preboss",
            templateKey = "DirectPreboss",
            tags = {},
            exits = { { index = 1, targetMode = "fixedBoss", type = "ShipsExitDoor" } },
            rewardSurfaceKey = "WorldShop",
            entryOfferPolicy = { kind = "shopOnly" },
            encounterProfileKey = "Preboss",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { min = 7 },
                code = "biome_depth_out_of_range",
            },
            force = { axis = "biomeDepthCache", deadline = 7, kind = "depthWindow", start = 7 },
            terminal = true,
            fixed = true,
            localChildren = {},
        },
    },
    canonicalCapacity = {
        {
            candidateConstraints = { templateKey = "ShipCombat" },
            contexts = {
                { biomeDepthCache = 1, count = 1 },
                { biomeDepthCache = 2, count = 1 },
                { biomeDepthCache = 3, count = 1 },
                { biomeDepthCache = 4, count = 1 },
                { biomeDepthCache = 5, count = 1 },
                { biomeDepthCache = 6, count = 1 },
            },
            familyKey = "O_ShipCombat",
        },
    },
}
