return {
    key = "P",
    label = "Mount Olympus",
    routeKey = "Surface",
    biomeStepKey = "Surface_P",
    layout = {
        kind = "LinearBiome",
        start = { mode = "fixed", roomKeys = { "P_Intro" } },
        continuation = { defaultBatchRuleKey = "Standard", overrides = {} },
        terminal = {
            roomKey = "P_PreBoss01",
            transitionRuleKey = "PrebossEntry",
            exitPolicy = { kind = "allExitsTerminal" },
        },
        bounds = { maxBatches = 9, maxTargets = 18 },
    },
    rooms = {
        {
            key = "P_Intro",
            label = "Entrance",
            kind = "Intro",
            templateKey = "FixedIntro",
            tags = { "Outdoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusOutdoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusOutdoorExitDoor" },
            },
            incomingReward = { kind = "none" },
            encounterProfileKey = "FixedIntro",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { exact = 1 },
                code = "biome_depth_out_of_range",
            },
            force = { kind = "always" },
            localChildren = {},
        },
        {
            key = "P_Combat01",
            label = "Combat 01",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Outdoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusOutdoorExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { min = 3 },
                code = "biome_encounter_depth_out_of_range",
            },
            canonicalFamily = "P_OutdoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat02",
            label = "Combat 02",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Indoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusIndoorExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "biome_depth_out_of_range",
            },
            canonicalFamily = "P_IndoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat03",
            label = "Combat 03",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Outdoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusOutdoorExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { max = 4 },
                code = "biome_encounter_depth_out_of_range",
            },
            canonicalFamily = "P_OutdoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat04",
            label = "Combat 04",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Indoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusIndoorExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "biome_depth_out_of_range",
            },
            canonicalFamily = "P_IndoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat05",
            label = "Combat 05",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Outdoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusOutdoorExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "P_OutdoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat06",
            label = "Combat 06",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Outdoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusOutdoorExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "P_OutdoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat07",
            label = "Combat 07",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Indoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusIndoorExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "biome_depth_out_of_range",
            },
            canonicalFamily = "P_IndoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat08",
            label = "Combat 08",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Indoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusIndoorExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "biome_depth_out_of_range",
            },
            canonicalFamily = "P_IndoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat09",
            label = "Combat 09",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Indoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusIndoorExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "biome_depth_out_of_range",
            },
            canonicalFamily = "P_IndoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat10",
            label = "Combat 10",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Indoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusIndoorExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "biome_depth_out_of_range",
            },
            canonicalFamily = "P_IndoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat11",
            label = "Combat 11",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Outdoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusOutdoorExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "P_OutdoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat12",
            label = "Combat 12",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Indoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusIndoorExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "biome_depth_out_of_range",
            },
            canonicalFamily = "P_IndoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat13",
            label = "Combat 13",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Outdoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusOutdoorExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "P_OutdoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat14",
            label = "Combat 14",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Outdoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusOutdoorExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "P_OutdoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat15",
            label = "Combat 15",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Indoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusIndoorExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "biome_depth_out_of_range",
            },
            canonicalFamily = "P_IndoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat16",
            label = "Combat 16",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Outdoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusOutdoorExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "P_OutdoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat17",
            label = "Combat 17",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Outdoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusOutdoorExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { min = 3 },
                code = "biome_encounter_depth_out_of_range",
            },
            canonicalFamily = "P_OutdoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat18",
            label = "Combat 18",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Indoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusIndoorExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { min = 2 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "CounterRange",
                        axis = "biomeEncounterDepth",
                        range = { min = 3 },
                        code = "biome_encounter_depth_out_of_range",
                    },
                },
            },
            canonicalFamily = "P_IndoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat19",
            label = "Combat 19",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Outdoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusOutdoorExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            canonicalFamily = "P_OutdoorCombat",
            localChildren = {},
        },
        {
            key = "P_Story01",
            label = "Dionysus",
            kind = "Story",
            templateKey = "Story",
            tags = { "Indoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusOutdoorExitDoor" },
            },
            incomingReward = { kind = "fixed", rewardType = "Story", constraints = {} },
            encounterProfileKey = "Story",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeEncounterDepth",
                        range = { minExclusive = 2 },
                        code = "biome_encounter_depth_out_of_range",
                    },
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { max = 7 },
                        code = "biome_depth_out_of_range",
                    },
                },
            },
            localChildren = {},
        },
        {
            key = "P_Reprieve01",
            label = "Fountain",
            kind = "Reprieve",
            templateKey = "Fountain",
            tags = { "Indoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusIndoorExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "HealthRestore",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { max = 7, min = 4 },
                code = "biome_depth_out_of_range",
            },
            localChildren = {},
        },
        {
            key = "P_Shop01",
            label = "Midshop",
            kind = "Shop",
            templateKey = "Shop",
            tags = { "Outdoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusOutdoorExitDoor" },
            },
            incomingReward = { kind = "shop", shopProfileKey = "WorldShop" },
            encounterProfileKey = "Shop",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeEncounterDepth",
                        range = { minExclusive = 4 },
                        code = "biome_encounter_depth_out_of_range",
                    },
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { max = 7 },
                        code = "biome_depth_out_of_range",
                    },
                },
            },
            localChildren = {},
        },
        {
            key = "P_MiniBoss01",
            label = "Talos",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = { "Indoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusIndoorExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress" }, eligibleRewardTypes = { "Boon" }, ineligibleRewardTypes = {} },
            encounterProfileKey = "P_MiniBoss01",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { min = 4 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RoomEnteredCount",
                        roomKeys = { "P_MiniBoss02" },
                        comparison = "==",
                        value = 0,
                        code = "other_miniboss_entered",
                    },
                    {
                        kind = "RequiredMinExits",
                        count = 2,
                        code = "insufficient_exits",
                    },
                },
            },
            force = { axis = "biomeDepthCache", deadline = 7, kind = "depthWindow", start = 4 },
            localChildren = {},
        },
        {
            key = "P_MiniBoss02",
            label = "Mega-Dracon",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = { "Indoor" },
            exits = { { index = 1, targetMode = "generated", type = "OlympusOutdoorExitDoor" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress" }, eligibleRewardTypes = { "Boon" }, ineligibleRewardTypes = {} },
            encounterProfileKey = "P_MiniBoss02",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { min = 4 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RoomEnteredCount",
                        roomKeys = { "P_MiniBoss01" },
                        comparison = "==",
                        value = 0,
                        code = "other_miniboss_entered",
                    },
                    {
                        kind = "RequiredMinExits",
                        count = 2,
                        code = "insufficient_exits",
                    },
                },
            },
            force = { axis = "biomeDepthCache", deadline = 7, kind = "depthWindow", start = 4 },
            localChildren = {},
        },
        {
            key = "P_PreBoss01",
            label = "Preboss",
            kind = "Preboss",
            templateKey = "ForkedPreboss",
            tags = {},
            exits = { { index = 1, targetMode = "fixedBoss", type = "OlympusIndoorExitDoor" } },
            incomingReward = { kind = "shop", shopProfileKey = "WorldShop" },
            entryOfferPolicy = {
                kind = "shopThenFillRemainingExits",
                defaultEntryMode = "Shop",
                freeReward = { kind = "countedChoice", storeKeys = { "RunProgress" }, eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion", "RoomMoneyDrop" } },
                maxFreeRewards = 1,
            },
            encounterProfileKey = "Preboss",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { min = 9 },
                code = "biome_depth_out_of_range",
            },
            force = { axis = "biomeDepthCache", deadline = 9, kind = "depthWindow", start = 9 },
            localChildren = {},
        },
    },
    canonicalCapacity = {
        {
            candidateConstraints = { requiredTags = { "Indoor" }, templateKey = "OlympusCombat" },
            contexts = { { biomeDepthCache = 3, biomeEncounterDepth = 3, count = 9 } },
            familyKey = "P_IndoorCombat",
        },
        {
            candidateConstraints = { requiredTags = { "Outdoor" }, templateKey = "OlympusCombat" },
            contexts = { { biomeDepthCache = 3, biomeEncounterDepth = 3, count = 10 } },
            familyKey = "P_OutdoorCombat",
        },
    },
}
