return {
    key = "P",
    label = "Mount Olympus",
    routeKey = "Surface",
    biomeStepKey = "Surface_P",
    root = { mode = "fixed", roomKeys = { "P_Intro" } },
    terminalRoomKeys = { "P_PreBoss01" },
    batchRuleKey = "Standard",
    topologyBounds = { maxBatches = 9, maxLocalChildrenPerRoom = 0, maxTargets = 18 },
    rooms = {
        {
            key = "P_Intro",
            kind = "Intro",
            templateKey = "FixedIntro",
            tags = { "Outdoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusOutdoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusOutdoorExitDoor" },
            },
            rewardSurfaceKey = "None",
            encounterProfileKey = "FixedIntro",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { exact = 1 },
                code = "biome_depth_out_of_range",
            },
            force = { kind = "always" },
            terminal = false,
            fixed = true,
            localChildren = {},
        },
        {
            key = "P_Combat01",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Outdoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusOutdoorExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { min = 3 },
                code = "biome_encounter_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "P_OutdoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat02",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Indoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusIndoorExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "biome_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "P_IndoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat03",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Outdoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusOutdoorExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { max = 4 },
                code = "biome_encounter_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "P_OutdoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat04",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Indoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusIndoorExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "biome_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "P_IndoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat05",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Outdoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusOutdoorExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "P_OutdoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat06",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Outdoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusOutdoorExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "P_OutdoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat07",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Indoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusIndoorExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "biome_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "P_IndoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat08",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Indoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusIndoorExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "biome_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "P_IndoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat09",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Indoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusIndoorExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "biome_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "P_IndoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat10",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Indoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusIndoorExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "biome_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "P_IndoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat11",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Outdoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusOutdoorExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "P_OutdoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat12",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Indoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusIndoorExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "biome_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "P_IndoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat13",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Outdoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusOutdoorExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "P_OutdoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat14",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Outdoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusOutdoorExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "P_OutdoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat15",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Indoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusIndoorExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "biome_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "P_IndoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat16",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Outdoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusOutdoorExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "P_OutdoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat17",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Outdoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusOutdoorExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeEncounterDepth",
                range = { min = 3 },
                code = "biome_encounter_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "P_OutdoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat18",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Indoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusIndoorExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { min = 2 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "CounterRange",
                        axis = "biomeEncounterDepth",
                        range = { min = 3 },
                        code = "biome_encounter_depth_out_of_range",
                    },
                },
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "P_IndoorCombat",
            localChildren = {},
        },
        {
            key = "P_Combat19",
            kind = "Combat",
            templateKey = "OlympusCombat",
            tags = { "Outdoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusOutdoorExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "OlympusCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            terminal = false,
            fixed = false,
            canonicalFamily = "P_OutdoorCombat",
            localChildren = {},
        },
        {
            key = "P_Story01",
            kind = "Story",
            templateKey = "Story",
            tags = { "Indoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusOutdoorExitDoor" },
            },
            rewardSurfaceKey = "FixedStory",
            encounterProfileKey = "Story",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeEncounterDepth",
                        range = { minExclusive = 2 },
                        code = "biome_encounter_depth_out_of_range",
                    },
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { max = 7 },
                        code = "biome_depth_out_of_range",
                    },
                },
            },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "P_Reprieve01",
            kind = "Reprieve",
            templateKey = "Fountain",
            tags = { "Indoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusIndoorExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "HealthRestore",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { max = 7, min = 4 },
                code = "biome_depth_out_of_range",
            },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "P_Shop01",
            kind = "Shop",
            templateKey = "Shop",
            tags = { "Outdoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusOutdoorExitDoor" },
            },
            rewardSurfaceKey = "WorldShop",
            encounterProfileKey = "Shop",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeEncounterDepth",
                        range = { minExclusive = 4 },
                        code = "biome_encounter_depth_out_of_range",
                    },
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { max = 7 },
                        code = "biome_depth_out_of_range",
                    },
                },
            },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "P_MiniBoss01",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = { "Indoor" },
            exits = {
                { index = 1, targetMode = "generated", type = "OlympusIndoorExitDoor" },
                { index = 2, targetMode = "generated", type = "OlympusIndoorExitDoor" },
            },
            rewardSurfaceKey = "RunProgressBoonOnly",
            encounterProfileKey = "P_MiniBoss01",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { min = 4 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RoomEnteredCount",
                        roomKeys = { "P_MiniBoss02" },
                        comparison = "==",
                        value = 0,
                        code = "other_miniboss_entered",
                    },
                    {
                        kind = "RequiredMinExits",
                        count = 2,
                        code = "insufficient_exits",
                    },
                },
            },
            force = { axis = "biomeDepthCache", deadline = 7, kind = "depthWindow", start = 4 },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "P_MiniBoss02",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = { "Indoor" },
            exits = { { index = 1, targetMode = "generated", type = "OlympusOutdoorExitDoor" } },
            rewardSurfaceKey = "RunProgressBoonOnly",
            encounterProfileKey = "P_MiniBoss02",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1, maxCreationsThisRun = 1 },
            eligibility = {
                kind = "All",
                requirements = {
                    {
                        kind = "CounterRange",
                        axis = "biomeDepthCache",
                        range = { min = 4 },
                        code = "biome_depth_out_of_range",
                    },
                    {
                        kind = "RoomEnteredCount",
                        roomKeys = { "P_MiniBoss01" },
                        comparison = "==",
                        value = 0,
                        code = "other_miniboss_entered",
                    },
                    {
                        kind = "RequiredMinExits",
                        count = 2,
                        code = "insufficient_exits",
                    },
                },
            },
            force = { axis = "biomeDepthCache", deadline = 7, kind = "depthWindow", start = 4 },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "P_PreBoss01",
            kind = "Preboss",
            templateKey = "Preboss",
            tags = {},
            exits = { { index = 1, targetMode = "fixedBoss", type = "OlympusIndoorExitDoor" } },
            rewardSurfaceKey = "PrebossShopOrFreeReward",
            encounterProfileKey = "Preboss",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { min = 9 },
                code = "biome_depth_out_of_range",
            },
            force = { axis = "biomeDepthCache", deadline = 9, kind = "depthWindow", start = 9 },
            terminal = true,
            fixed = true,
            localChildren = {},
        },
    },
    canonicalCapacity = {
        {
            candidateConstraints = { requiredTags = { "Indoor" }, templateKey = "OlympusCombat" },
            contexts = { { biomeDepthCache = 3, biomeEncounterDepth = 3, count = 9 } },
            familyKey = "P_IndoorCombat",
        },
        {
            candidateConstraints = { requiredTags = { "Outdoor" }, templateKey = "OlympusCombat" },
            contexts = { { biomeDepthCache = 3, biomeEncounterDepth = 3, count = 10 } },
            familyKey = "P_OutdoorCombat",
        },
    },
}
