return {
    key = "Q",
    label = "Summit",
    routeKey = "Surface",
    biomeStepKey = "Surface_Q",
    root = { mode = "fixed", roomKeys = { "Q_Intro" } },
    terminalRoomKeys = { "Q_PreBoss01" },
    batchRuleKey = "Standard",
    specializedBatchRuleKeys = { "QMinibossBatch" },
    topologyBounds = { maxBatches = 7, maxLocalChildrenPerRoom = 0, maxTargets = 10 },
    deterministicPairs = {
        { biomeDepthCache = 3, key = "Q_Depth3Minibosses", roomKeys = { "Q_MiniBoss02", "Q_MiniBoss05" } },
        { biomeDepthCache = 6, key = "Q_Depth6Minibosses", roomKeys = { "Q_MiniBoss03", "Q_MiniBoss04" } },
    },
    rooms = {
        {
            key = "Q_Intro",
            kind = "Intro",
            templateKey = "FixedIntro",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "FortressMainDoor" } },
            rewardSurfaceKey = "OpeningReward",
            encounterProfileKey = "FixedIntro",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeDepthCache",
                range = { exact = 1 },
                code = "q_intro_depth",
            },
            force = { axis = "biomeDepthCache", deadline = 1, kind = "depthWindow", start = 1 },
            terminal = false,
            fixed = true,
            localChildren = {},
        },
        {
            key = "Q_Combat01",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "TyphonExitDoor" } },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeDepthCache",
                range = { maxExclusive = 7 },
                code = "q_combat01_depth",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "Q_OneExitCombat",
            localChildren = {},
        },
        {
            key = "Q_Combat02",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "TyphonExitDoor" } },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeDepthCache",
                range = { maxExclusive = 7 },
                code = "q_combat02_depth",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "Q_OneExitCombat",
            localChildren = {},
        },
        {
            key = "Q_Combat03",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "TyphonExitDoor" },
                { index = 2, targetMode = "generated", type = "TyphonExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "q_combat03_depth",
            },
            force = { axis = "biomeDepthCache", deadline = 2, kind = "depthWindow", start = 2 },
            terminal = false,
            fixed = false,
            canonicalFamily = "Q_TwoExitCombat",
            localChildren = {},
        },
        {
            key = "Q_Combat04",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "TyphonExitDoor" } },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeDepthCache",
                range = { maxExclusive = 7 },
                code = "q_combat04_depth",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "Q_OneExitCombat",
            localChildren = {},
        },
        {
            key = "Q_Combat05",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "TyphonExitDoor" },
                { index = 2, targetMode = "generated", type = "TyphonExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "q_combat05_depth",
            },
            force = { axis = "biomeDepthCache", deadline = 2, kind = "depthWindow", start = 2 },
            terminal = false,
            fixed = false,
            canonicalFamily = "Q_TwoExitCombat",
            localChildren = {},
        },
        {
            key = "Q_Combat06",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "TyphonExitDoor" } },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeDepthCache",
                range = { minExclusive = 3 },
                code = "q_combat06_depth",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "Q_OneExitCombat",
            localChildren = {},
        },
        {
            key = "Q_Combat07",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "TyphonExitDoor" } },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "q_combat07_depth",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "Q_OneExitCombat",
            localChildren = {},
        },
        {
            key = "Q_Combat08",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "TyphonExitDoor" } },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeDepthCache",
                range = { maxExclusive = 7 },
                code = "q_combat08_depth",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "Q_OneExitCombat",
            localChildren = {},
        },
        {
            key = "Q_Combat09",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "TyphonExitDoor" } },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeDepthCache",
                range = { minExclusive = 3 },
                code = "q_combat09_depth",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "Q_OneExitCombat",
            localChildren = {},
        },
        {
            key = "Q_Combat12",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "TyphonExitDoor" },
                { index = 2, targetMode = "generated", type = "TyphonExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "q_combat12_depth",
            },
            force = { axis = "biomeDepthCache", deadline = 5, kind = "depthWindow", start = 5 },
            terminal = false,
            fixed = false,
            canonicalFamily = "Q_TwoExitCombat",
            localChildren = {},
        },
        {
            key = "Q_Combat13",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "TyphonExitDoor" },
                { index = 2, targetMode = "generated", type = "TyphonExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "q_combat13_depth",
            },
            force = { axis = "biomeDepthCache", deadline = 5, kind = "depthWindow", start = 5 },
            terminal = false,
            fixed = false,
            canonicalFamily = "Q_TwoExitCombat",
            localChildren = {},
        },
        {
            key = "Q_Combat14",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "TyphonExitDoor" },
                { index = 2, targetMode = "generated", type = "TyphonExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "q_combat14_depth",
            },
            force = { axis = "biomeDepthCache", deadline = 5, kind = "depthWindow", start = 5 },
            terminal = false,
            fixed = false,
            canonicalFamily = "Q_TwoExitCombat",
            localChildren = {},
        },
        {
            key = "Q_Combat15",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "TyphonExitDoor" },
                { index = 2, targetMode = "generated", type = "TyphonExitDoor" },
            },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "q_combat15_depth",
            },
            force = { axis = "biomeDepthCache", deadline = 2, kind = "depthWindow", start = 2 },
            terminal = false,
            fixed = false,
            canonicalFamily = "Q_TwoExitCombat",
            localChildren = {},
        },
        {
            key = "Q_Combat16",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "TyphonExitDoor" } },
            rewardSurfaceKey = "RunProgressMinorMajor",
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "q_combat16_depth",
            },
            terminal = false,
            fixed = false,
            canonicalFamily = "Q_OneExitCombat",
            localChildren = {},
        },
        {
            key = "Q_MiniBoss02",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "TyphonExitDoor" } },
            rewardSurfaceKey = "TyphonBossReward",
            encounterProfileKey = "MiniBossBrute",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeDepthCache",
                range = { exact = 3 },
                code = "q_miniboss02_depth",
            },
            force = { axis = "biomeDepthCache", deadline = 3, kind = "depthWindow", start = 3 },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "Q_MiniBoss05",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "TyphonExitDoor" } },
            rewardSurfaceKey = "TyphonBossReward",
            encounterProfileKey = "Q_MiniBoss05",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeDepthCache",
                range = { exact = 3 },
                code = "q_miniboss05_depth",
            },
            force = { axis = "biomeDepthCache", deadline = 3, kind = "depthWindow", start = 3 },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "Q_MiniBoss03",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "TyphonExitDoor" } },
            rewardSurfaceKey = "TyphonBossReward",
            encounterProfileKey = "Q_MiniBoss03",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeDepthCache",
                range = { exact = 6 },
                code = "q_miniboss03_depth",
            },
            force = { axis = "biomeDepthCache", deadline = 6, kind = "depthWindow", start = 6 },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "Q_MiniBoss04",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "TyphonExitDoor" } },
            rewardSurfaceKey = "TyphonBossReward",
            encounterProfileKey = "Q_MiniBoss04",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeDepthCache",
                range = { exact = 6 },
                code = "q_miniboss04_depth",
            },
            force = { axis = "biomeDepthCache", deadline = 6, kind = "depthWindow", start = 6 },
            terminal = false,
            fixed = false,
            localChildren = {},
        },
        {
            key = "Q_PreBoss01",
            kind = "Preboss",
            templateKey = "Preboss",
            tags = {},
            exits = { { index = 1, targetMode = "fixedBoss", type = "FortressMainDoor" } },
            rewardSurfaceKey = "SummitShop",
            encounterProfileKey = "Preboss",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                phase = "room.generate_next",
                axis = "biomeDepthCache",
                range = { min = 7 },
                code = "q_preboss_too_early",
            },
            force = { axis = "biomeDepthCache", deadline = 7, kind = "depthWindow", start = 7 },
            terminal = true,
            fixed = true,
            localChildren = {},
        },
    },
    canonicalCapacity = {
        {
            candidateConstraints = { exitCount = 1, templateKey = "StandardCombat" },
            contexts = { { biomeDepthCache = 4, count = 8 } },
            familyKey = "Q_OneExitCombat",
        },
        {
            candidateConstraints = { exitCount = 2, templateKey = "StandardCombat" },
            contexts = { { biomeDepthCache = 2, count = 3 }, { biomeDepthCache = 5, count = 3 } },
            familyKey = "Q_TwoExitCombat",
        },
    },
}
