return {
    key = "Q",
    label = "Summit",
    routeKey = "Surface",
    biomeStepKey = "Surface_Q",
    layout = {
        kind = "LinearBiome",
        start = { mode = "fixed", roomKeys = { "Q_Intro" } },
        continuation = {
            defaultBatchRuleKey = "Standard",
            overrides = {
                {
                    key = "Q_Depth3Minibosses",
                    when = {
                        parentRoomKeys = { "Q_Combat03", "Q_Combat05", "Q_Combat15" },
                    },
                    batchRuleKey = "QMinibossBatch",
                    targetRoomKeys = { "Q_MiniBoss02", "Q_MiniBoss05" },
                },
                {
                    key = "Q_Depth6Minibosses",
                    when = {
                        parentRoomKeys = { "Q_Combat12", "Q_Combat13", "Q_Combat14" },
                    },
                    batchRuleKey = "QMinibossBatch",
                    targetRoomKeys = { "Q_MiniBoss03", "Q_MiniBoss04" },
                },
            },
        },
        terminal = {
            roomKey = "Q_PreBoss01",
            transitionRuleKey = "PrebossEntry",
            exitPolicy = { kind = "singleTerminal" },
        },
        bounds = { maxBatches = 7, maxTargets = 10 },
    },
    rooms = {
        {
            key = "Q_Intro",
            label = "Entrance",
            kind = "Intro",
            templateKey = "FixedIntro",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "FortressMainDoor" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress" }, eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion", "RoomMoneyDrop", "MaxHealthDrop", "MaxManaDrop" } },
            encounterProfileKey = "FixedIntro",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { exact = 1 },
                code = "biome_depth_out_of_range",
            },
            force = { axis = "biomeDepthCache", deadline = 1, kind = "depthWindow", start = 1 },
            localChildren = {},
        },
        {
            key = "Q_Combat01",
            label = "Combat 01",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "TyphonExitDoor" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { maxExclusive = 7 },
                code = "biome_depth_out_of_range",
            },
            canonicalFamily = "Q_OneExitCombat",
            localChildren = {},
        },
        {
            key = "Q_Combat02",
            label = "Combat 02",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "TyphonExitDoor" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { maxExclusive = 7 },
                code = "biome_depth_out_of_range",
            },
            canonicalFamily = "Q_OneExitCombat",
            localChildren = {},
        },
        {
            key = "Q_Combat03",
            label = "Combat 03",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "TyphonExitDoor" },
                { index = 2, targetMode = "generated", type = "TyphonExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "biome_depth_out_of_range",
            },
            force = { axis = "biomeDepthCache", deadline = 2, kind = "depthWindow", start = 2 },
            canonicalFamily = "Q_TwoExitCombat",
            localChildren = {},
        },
        {
            key = "Q_Combat04",
            label = "Combat 04",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "TyphonExitDoor" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { maxExclusive = 7 },
                code = "biome_depth_out_of_range",
            },
            canonicalFamily = "Q_OneExitCombat",
            localChildren = {},
        },
        {
            key = "Q_Combat05",
            label = "Combat 05",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "TyphonExitDoor" },
                { index = 2, targetMode = "generated", type = "TyphonExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "biome_depth_out_of_range",
            },
            force = { axis = "biomeDepthCache", deadline = 2, kind = "depthWindow", start = 2 },
            canonicalFamily = "Q_TwoExitCombat",
            localChildren = {},
        },
        {
            key = "Q_Combat06",
            label = "Combat 06",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "TyphonExitDoor" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { minExclusive = 3 },
                code = "biome_depth_out_of_range",
            },
            canonicalFamily = "Q_OneExitCombat",
            localChildren = {},
        },
        {
            key = "Q_Combat07",
            label = "Combat 07",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "TyphonExitDoor" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "biome_depth_out_of_range",
            },
            canonicalFamily = "Q_OneExitCombat",
            localChildren = {},
        },
        {
            key = "Q_Combat08",
            label = "Combat 08",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "TyphonExitDoor" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { maxExclusive = 7 },
                code = "biome_depth_out_of_range",
            },
            canonicalFamily = "Q_OneExitCombat",
            localChildren = {},
        },
        {
            key = "Q_Combat09",
            label = "Combat 09",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "TyphonExitDoor" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { minExclusive = 3 },
                code = "biome_depth_out_of_range",
            },
            canonicalFamily = "Q_OneExitCombat",
            localChildren = {},
        },
        {
            key = "Q_Combat12",
            label = "Combat 12",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "TyphonExitDoor" },
                { index = 2, targetMode = "generated", type = "TyphonExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "biome_depth_out_of_range",
            },
            force = { axis = "biomeDepthCache", deadline = 5, kind = "depthWindow", start = 5 },
            canonicalFamily = "Q_TwoExitCombat",
            localChildren = {},
        },
        {
            key = "Q_Combat13",
            label = "Combat 13",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "TyphonExitDoor" },
                { index = 2, targetMode = "generated", type = "TyphonExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "biome_depth_out_of_range",
            },
            force = { axis = "biomeDepthCache", deadline = 5, kind = "depthWindow", start = 5 },
            canonicalFamily = "Q_TwoExitCombat",
            localChildren = {},
        },
        {
            key = "Q_Combat14",
            label = "Combat 14",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "TyphonExitDoor" },
                { index = 2, targetMode = "generated", type = "TyphonExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "biome_depth_out_of_range",
            },
            force = { axis = "biomeDepthCache", deadline = 5, kind = "depthWindow", start = 5 },
            canonicalFamily = "Q_TwoExitCombat",
            localChildren = {},
        },
        {
            key = "Q_Combat15",
            label = "Combat 15",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = {
                { index = 1, targetMode = "generated", type = "TyphonExitDoor" },
                { index = 2, targetMode = "generated", type = "TyphonExitDoor" },
            },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "biome_depth_out_of_range",
            },
            force = { axis = "biomeDepthCache", deadline = 2, kind = "depthWindow", start = 2 },
            canonicalFamily = "Q_TwoExitCombat",
            localChildren = {},
        },
        {
            key = "Q_Combat16",
            label = "Combat 16",
            kind = "Combat",
            templateKey = "StandardCombat",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "TyphonExitDoor" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "RunProgress", "MetaProgress" }, defaultStoreKey = "RunProgress", eligibleRewardTypes = {}, ineligibleRewardTypes = { "Devotion" } },
            encounterProfileKey = "StandardCombat",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { min = 2 },
                code = "biome_depth_out_of_range",
            },
            canonicalFamily = "Q_OneExitCombat",
            localChildren = {},
        },
        {
            key = "Q_MiniBoss02",
            label = "Spawn of Typhon",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "TyphonExitDoor" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "TyphonBossRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
            encounterProfileKey = "MiniBossBrute",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { exact = 3 },
                code = "biome_depth_out_of_range",
            },
            force = { axis = "biomeDepthCache", deadline = 3, kind = "depthWindow", start = 3 },
            localChildren = {},
        },
        {
            key = "Q_MiniBoss05",
            label = "Twins of Typhon",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "TyphonExitDoor" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "TyphonBossRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
            encounterProfileKey = "Q_MiniBoss05",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { exact = 3 },
                code = "biome_depth_out_of_range",
            },
            force = { axis = "biomeDepthCache", deadline = 3, kind = "depthWindow", start = 3 },
            localChildren = {},
        },
        {
            key = "Q_MiniBoss03",
            label = "Tail of Typhon",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "TyphonExitDoor" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "TyphonBossRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
            encounterProfileKey = "Q_MiniBoss03",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { exact = 6 },
                code = "biome_depth_out_of_range",
            },
            force = { axis = "biomeDepthCache", deadline = 6, kind = "depthWindow", start = 6 },
            localChildren = {},
        },
        {
            key = "Q_MiniBoss04",
            label = "Eye of Typhon",
            kind = "Miniboss",
            templateKey = "Miniboss",
            tags = {},
            exits = { { index = 1, targetMode = "generated", type = "TyphonExitDoor" } },
            incomingReward = { kind = "countedChoice", storeKeys = { "TyphonBossRewards" }, eligibleRewardTypes = {}, ineligibleRewardTypes = {} },
            encounterProfileKey = "Q_MiniBoss04",
            counters = { biomeDepthCache = 1, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { exact = 6 },
                code = "biome_depth_out_of_range",
            },
            force = { axis = "biomeDepthCache", deadline = 6, kind = "depthWindow", start = 6 },
            localChildren = {},
        },
        {
            key = "Q_PreBoss01",
            label = "Preboss",
            kind = "Preboss",
            templateKey = "DirectPreboss",
            tags = {},
            exits = { { index = 1, targetMode = "fixedBoss", type = "FortressMainDoor" } },
            incomingReward = { kind = "shop", shopProfileKey = "Q_WorldShop" },
            entryOfferPolicy = { kind = "shopOnly" },
            encounterProfileKey = "Preboss",
            counters = { biomeDepthCache = 0, roomHistoryOrdinal = 1 },
            caps = { maxAppearancesThisBiome = 1 },
            eligibility = {
                kind = "CounterRange",
                axis = "biomeDepthCache",
                range = { min = 7 },
                code = "biome_depth_out_of_range",
            },
            force = { axis = "biomeDepthCache", deadline = 7, kind = "depthWindow", start = 7 },
            localChildren = {},
        },
    },
    canonicalCapacity = {
        {
            candidateConstraints = { exitCount = 1, templateKey = "StandardCombat" },
            contexts = { { biomeDepthCache = 4, count = 8 } },
            familyKey = "Q_OneExitCombat",
        },
        {
            candidateConstraints = { exitCount = 2, templateKey = "StandardCombat" },
            contexts = { { biomeDepthCache = 2, count = 3 }, { biomeDepthCache = 5, count = 3 } },
            familyKey = "Q_TwoExitCombat",
        },
    },
}
